// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';


class GeneratedLinearSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');

      final a = p.a - p.ra;
      final b = p.b - p.rb;

      if (a == 0) {
        final sat = _evalOp(b, p.op, 0);
        return SolveResult(
          answer: sat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: sat ? '(-∞, ∞)' : '∅',
        );
      }

      final boundary = -b / a;
      final finalOp = a < 0 ? _flipOp(p.op) : p.op;
      return SolveResult(
        answer: 'x $finalOp ${_fmt(boundary)}',
        points: [boundary],
        intervalNotation: _interval(finalOp, boundary),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      title: 'Original Inequality',
      explanation: 'Start with the given inequality.',
      latex: input.trim(),
    ));

    final a = p.a - p.ra;
    final b = p.b - p.rb;

    if (p.ra != 0 || p.rb != 0) {
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Move All Terms to One Side',
        explanation: 'Bring all terms to one side to compare with zero.',
        latex: '${_coefLatex(a)}x ${b >= 0 ? "+ ${_fmtLatex(b)}" : "- ${_fmtLatex(b.abs())}"} ${_texOp(p.op)} 0',
      ));
    }

    if (a == 0) {
      final sat = _evalOp(b, p.op, 0);
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Evaluate Truth',
        explanation: sat ? 'The statement is always true.' : 'The statement is always false.',
        latex: sat ? r'(-\infty, \infty)' : r'\emptyset',
      ));
      return steps;
    }

    if (b != 0) {
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Isolate Term',
        explanation: 'Move the constant to the other side.',
        latex: '${_coefLatex(a)}x ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b)}',
      ));
    }

    if (a != 1 && a != -1) {
      final flip = a < 0;
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Divide by ${_fmt(a)}',
        explanation: flip
            ? 'Divide by ${_fmt(a)} and flip the sign (negative coefficient).'
            : 'Divide by ${_fmt(a)} to isolate x.',
        latex: 'x ${_texOp(flip ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b / a)}',
      ));
    }

    final finalOp = a < 0 ? _flipOp(p.op) : p.op;
    steps.add(StepModel(
      stepNumber: n++,
      title: 'Solution',
      explanation: 'The complete solution set.',
      latex: _intervalLatex(finalOp, -b / a),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = _normalize(input);
    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);
    if (left.isEmpty || right.isEmpty) return null;

    final lp = _parseLinear(left);
    final rp = _parseLinear(right);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['x']!, b: lp['c']!,
      ra: rp['x']!, rb: rp['c']!,
    );
  }

  static String _normalize(String input) {
    return input
        .trim()
        .replaceAll('\u2212', '-')
        .replaceAll(' ', '')
        .replaceAll('>=', '≥')
        .replaceAll('<=', '≤')
        .replaceAll('=>', '≥')
        .replaceAll('=<', '≤')
        .replaceAll('x²', 'x^2')
        .replaceAll('²', '^2');
  }

  static String? _extractOp(String s) {
    if (s.contains('≥')) return '≥';
    if (s.contains('≤')) return '≤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _texOp(String op) {
    switch (op) {
      case '≥': return '\\geq';
      case '≤': return '\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }

  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '≥': return '≤';
      case '≤': return '≥';
      default: return op;
    }
  }

  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '≥': return left >= right;
      case '≤': return left <= right;
      default: return false;
    }
  }

  static String _intervalLatex(String op, double b) {
    final bs = _fmtLatex(b);
    switch (op) {
      case '>': return '($bs, \infty)';
      case '≥': return '[$bs, \infty)';
      case '<': return '(-\infty, $bs)';
      case '≤': return '(-\infty, $bs]';
      default: return '';
    }
  }


  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, ∞)';
      case '≥': return '[$bs, ∞)';
      case '<': return '(-∞, $bs)';
      case '≤': return '(-∞, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, ra, rb;
  const _Parsed({required this.op, required this.a, required this.b, required this.ra, required this.rb});
}
