// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';


class GeneratedRadicalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse radical inequality.');

      // For sqrt(bx + c) op k
      if (p.k < 0) {
        if (p.op == '>' || p.op == '≥') {
          return SolveResult(answer: 'x ≥ ${_fmt(-p.c / p.b)} (domain only)', points: [], intervalNotation: '');
        }
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
      }

      // Domain: bx + c >= 0  =>  x >= -c/b (if b > 0) or x <= -c/b (if b < 0)
      final domainBoundary = -p.c / p.b;
      final domainReversed = p.b < 0;

      // Square: bx + c op k^2  =>  x op (k^2 - c) / b
      final kSq = p.k * p.k;
      final squaredBoundary = (kSq - p.c) / p.b;

      // Combine domain and squared inequality
      // Case analysis based on operation
      String answer, interval;
      final f = _fmt;
      final dB = f(domainBoundary);
      final sB = f(squaredBoundary);

      if (p.op == '<' || p.op == '≤') {
        // sqrt(...) < k => domain AND x < (k^2 - c)/b
        // Upper bound is min of what?
        if (domainReversed) {
          answer = '$sB ≤ x ≤ $dB';
          interval = '[$sB, $dB]';
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'No solution';
            interval = '∅';
          } else {
            answer = '$dB ≤ x $sB';
            interval = '[$dB, $sB]';
          }
        }
      } else {
        // sqrt(...) > k => domain AND x > (k^2 - c)/b
        if (domainReversed) {
          if (squaredBoundary < domainBoundary) {
            answer = 'x ≥ $dB';
            interval = '[$dB, ∞)';
          } else {
            answer = 'x ≥ $sB';
            interval = '[$sB, ∞)';
          }
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'x ≥ $dB';
            interval = '[$dB, ∞)';
          } else {
            answer = 'x ≥ $sB';
            interval = '[$sB, ∞)';
          }
        }
      }

      final pts = <double>[domainBoundary];
      if (squaredBoundary.isFinite && squaredBoundary != domainBoundary) {
        pts.add(squaredBoundary);
      }
      pts.sort();

      return SolveResult(answer: answer, points: pts, intervalNotation: interval);
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      title: 'Original Inequality',
      explanation: 'Start with the radical inequality.',
      latex: input.trim(),
    ));

    final radStr = _linearStr(p.b, p.c);
    final radStrLatex = _linearStrLatex(p.b, p.c);
    steps.add(StepModel(
      stepNumber: n++,
      title: 'Domain',
      explanation: 'Radicand must be non-negative: $radStr ≥ 0',
      latex: r'\text{' + radStrLatex + r'} \geq 0',
    ));

    if (p.k >= 0) {
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Square Both Sides',
        explanation: 'Square to eliminate the radical.',
        latex: '$radStrLatex ${_texOp(p.op)} ${_fmtLatex(p.k * p.k)}',
      ));
    }

    steps.add(StepModel(
      stepNumber: n++,
      title: 'Solution',
      explanation: 'Combine conditions.',
      latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .toLowerCase()
        .replaceAll(' ', '')
        .replaceAll('>=', '≥')
        .replaceAll('<=', '≤')
        .replaceAll('²', '^2')
        .replaceAll('\u221a', 'sqrt');

    final op = _extractOp(s);
    if (op == null) return null;

    // Find operator at top level (not inside parentheses)
    int depth = 0;
    int opIdx = -1;
    for (int i = 0; i < s.length; i++) {
      if (s[i] == '(') depth++;
      if (s[i] == ')') depth--;
      if (depth != 0) continue;
      if (s[i] == op) {
        // Check for multi-char ops
        if (op == '≥' && i > 0) {
          if (s[i - 1] == '>') continue; // already matched with >
        }
        opIdx = i;
        break;
      }
    }
    if (opIdx == -1) return null;

    final lhs = s.substring(0, opIdx);
    final rhs = s.substring(opIdx + op.length);

    bool sqrtOnLeft = lhs.contains('sqrt');
    bool sqrtOnRight = rhs.contains('sqrt');
    if (!sqrtOnLeft && !sqrtOnRight) return null;

    String sqrtSide = sqrtOnLeft ? lhs : rhs;
    String constSide = sqrtOnLeft ? rhs : lhs;

    final sqrtMatch = RegExp(r'sqrt\(([^)]+)\)').firstMatch(sqrtSide);
    if (sqrtMatch == null) return null;
    final radicand = sqrtMatch.group(1)!;

    final k = double.tryParse(constSide.trim());
    if (k == null) return null;

    final parsed = _parseLinear(radicand);
    if (parsed == null) return null;

    return _Parsed(op: op, b: parsed['x']!, c: parsed['c']!, k: k);
  }

  static String? _extractOp(String s) {
    if (s.contains('≥')) return '≥';
    if (s.contains('≤')) return '≤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _linearStr(double a, double c) {
    if (a == 0) return _fmt(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmt(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmt(c.abs())}';
  }

  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\u221e', r'\infty')
        .replaceAll('\u2205', r'\emptyset')
        .replaceAll('\u222a', r'\cup');
  }

  static String _texOp(String op) {
    switch (op) {
      case '≥': return '\\geq';
      case '≤': return '\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }

}

class _Parsed {
  final String op;
  final double b, c, k;
  const _Parsed({required this.op, required this.b, required this.c, required this.k});
}
