// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';

import 'dart:math' as math;

class GeneratedQuadraticSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');
      if (p.a == 0 && p.b == 0 && p.c == 0) {
        return SolveResult.error('Could not parse quadratic inequality.');
      }
      if (p.a == 0) return _solveLinear(p.b, p.c, p.op);

      final disc = p.b * p.b - 4 * p.a * p.c;

      if (disc < 0) {
        final allSat = p.a > 0
            ? (p.op == '>' || p.op == '≥')
            : (p.op == '<' || p.op == '≤');
        return SolveResult(
          answer: allSat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: allSat ? '(-∞, ∞)' : '∅',
        );
      }

      final sqrtD = math.sqrt(disc);
      final r1 = (-p.b - sqrtD) / (2 * p.a);
      final r2 = (-p.b + sqrtD) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;

      if (disc == 0) {
        final root = -p.b / (2 * p.a);
        if (p.op == '≤' || p.op == '≥') {
          final ans = p.op == '≤' ? 'x = ${_fmt(root)}' : 'All real numbers';
          final interval = p.op == '≤' ? '{${_fmt(root)}}' : '(-∞, ∞)';
          return SolveResult(answer: ans, points: [root], intervalNotation: interval);
        } else {
          final ans = p.op == '<' ? 'No solution' : 'x ≥ ${_fmt(root)}';
          final interval = p.op == '<'
              ? '∅'
              : '(-∞, ${_fmt(root)}) ∪ (${_fmt(root)}, ∞)';
          return SolveResult(answer: ans, points: [root], intervalNotation: interval);
        }
      }

      final strict = p.op == '<' || p.op == '>';
      final lb = strict ? '(' : '[';
      final rb = strict ? ')' : ']';
      final between = (p.op == '<' || p.op == '≤') ? p.a > 0 : p.a < 0;

      if (between) {
        return SolveResult(
          answer: '${_fmt(lo)} ${p.op} x ${p.op} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '$lb${_fmt(lo)}, ${_fmt(hi)}$rb',
        );
      } else {
        final flipOp = _flipOp(p.op);
        return SolveResult(
          answer: 'x $flipOp ${_fmt(lo)} or x ${p.op} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '(-∞, ${_fmt(lo)})$rb ∪ $lb${_fmt(hi)}, ∞)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final disc = p.b * p.b - 4 * p.a * p.c;

    if (disc < 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Discriminant \\Delta = ${_fmt(disc)} < 0 — no real roots',
        details: [
          r'\Delta = b^2 - 4ac = ' + '${_fmtLatex(p.b)}^2 - 4(${_fmtLatex(p.a)})(${_fmtLatex(p.c)}) = ${_fmtLatex(disc)} < 0',
          r'\text{No real roots, inequality is either always true or always false}',
        ],
        latex: '\\Delta = ${_fmtLatex(disc)} < 0 \\implies \text{No real roots}',
      ));
      final result = solve(input);
      steps.add(StepModel(
        stepNumber: n++,
        latex: r'\text{S.S} = ' + _toLatexInterval(result.intervalNotation ?? ''),
      ));
      return steps;
    }

    steps.add(StepModel(
      stepNumber: n++,
      hint: disc == 0 ? 'One repeated root' : 'Two distinct roots',
      details: [
        r'x = \frac{-b \pm \sqrt{\Delta}}{2a} = \frac{' + '${_fmtLatex(-p.b)} \pm \sqrt{${_fmtLatex(disc)}}' + r'}{2(' + '${_fmtLatex(p.a)}' + r')}',
        disc == 0
          ? r'x = ' + _fmtLatex(-p.b / (2 * p.a))
          : r'x_1 = ' + _fmtLatex((-p.b - math.sqrt(disc)) / (2 * p.a)) + r',\; x_2 = ' + _fmtLatex((-p.b + math.sqrt(disc)) / (2 * p.a)),
      ],
      latex: disc == 0
          ? r'x = ' + _fmtLatex(-p.b / (2 * p.a))
          : r'x_1 = ' + _fmtLatex((-p.b - math.sqrt(disc)) / (2 * p.a)) + ', x_2 = ' + _fmtLatex((-p.b + math.sqrt(disc)) / (2 * p.a)),

    ));

    if (disc > 0) {
      final r1 = (-p.b - math.sqrt(disc)) / (2 * p.a);
      final r2 = (-p.b + math.sqrt(disc)) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Test each region separated by the roots',
        latex: 'A: x < ${_fmtLatex(lo)}, B: ${_fmtLatex(lo)} < x < ${_fmtLatex(hi)}, C: x > ${_fmtLatex(hi)}',
      ));
    }

    final result = solve(input);
    steps.add(StepModel(
      stepNumber: n++,
      latex: r'\text{S.S} = ' + _toLatexInterval(result.intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('²', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '≥')
        .replaceAll('<=', '≤');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = _findOpIndex(s, op);
    if (idx == -1) return null;

    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final lp = _parseQuad(lhs);
    final rp = _parseQuad(rhs);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['a']! - rp['a']!,
      b: lp['b']! - rp['b']!,
      c: lp['c']! - rp['c']!,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('≥')) return '≥';
    if (s.contains('≤')) return '≤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static int _findOpIndex(String s, String op) {
    if (op == '>' || op == '<') {
      for (int i = s.length - 1; i >= 0; i--) {
        if (s[i] == op) {
          if (i + 1 < s.length && s[i + 1] == '=') continue;
          return i;
        }
      }
      return -1;
    }
    return s.indexOf(op);
  }

  static Map<String, double>? _parseQuad(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    double a = 0, b = 0, c = 0;
    final tokens = <String>[];
    int depth = 0;
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if (ch == '(') { depth++; cur += ch; }
      else if (ch == ')') { depth--; cur += ch; }
      else if ((ch == '+' || ch == '-') && i > 0 && depth == 0 && cur.isNotEmpty) {
        tokens.add(cur); cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      final t = tok.replaceAll('*', '');
      if (t.contains('x^2')) {
        final cs = t.substring(0, t.indexOf('x'));
        a += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else if (t.contains('x')) {
        final cs = t.substring(0, t.indexOf('x'));
        b += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else {
        final clean = t.startsWith('+') ? t.substring(1) : t;
        c += double.tryParse(clean) ?? 0;
      }
    }
    return {'a': a, 'b': b, 'c': c};
  }

  static SolveResult _solveLinear(double b, double c, String op) {
    if (b == 0) {
      final sat = _evalOp(c, op, 0);
      return SolveResult(
        answer: sat ? 'All real numbers' : 'No solution',
        points: [],
        intervalNotation: sat ? '(-∞, ∞)' : '∅',
      );
    }
    final x = -c / b;
    final finalOp = b < 0 ? _flipOp(op) : op;
    return SolveResult(
      answer: 'x $finalOp ${_fmt(x)}',
      points: [x],
      intervalNotation: _interval(finalOp, x),
    );
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\u221e', r'\infty')
        .replaceAll('\u2205', r'\emptyset')
        .replaceAll('\u222a', r'\cup');
  }

  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '≥': return '≤';
      case '≤': return '≥';
      default: return op;
    }
  }

  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '≥': return left >= right;
      case '≤': return left <= right;
      default: return false;
    }
  }


  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, ∞)';
      case '≥': return '[$bs, ∞)';
      case '<': return '(-∞, $bs)';
      case '≤': return '(-∞, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, c;
  const _Parsed({required this.op, required this.a, required this.b, required this.c});
}
