// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.
import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';


class GeneratedAbsoluteSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse absolute value inequality.');

      bool absOnLeft = p.absOnLeft;
      String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
      final isNarrow = effectiveOp == '<' || effectiveOp == '≤';

      if (isNarrow) {
        if (p.k < 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '<') return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '≤') {
          if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
          final root = -p.b / p.a;
          return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
        }
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final lb = effectiveOp == '<' ? '(' : '[';
        final rb = effectiveOp == '<' ? ')' : ']';
        return SolveResult(
          answer: '${_fmt(l)} $effectiveOp x $effectiveOp ${_fmt(h)}',
          points: [l, h],
          intervalNotation: '$lb${_fmt(l)}, ${_fmt(h)}$rb',
        );
      } else {
        if (p.k < 0) return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
        if (p.k == 0 && effectiveOp == '≥') return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '>') {
          final root = -p.b / p.a;
          final fR = _fmt(root);
          return SolveResult(answer: 'x ≥ $fR', points: [root], intervalNotation: '(-∞, $fR) ∪ ($fR, ∞)');
        }

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final b1 = effectiveOp == '>' ? ')' : ']';
        final b2 = effectiveOp == '>' ? '(' : '[';
        final fL = _fmt(l);
        final fH = _fmt(h);
        final flipOp = _flipOp(effectiveOp);
        return SolveResult(
          answer: 'x $flipOp $fL or x $effectiveOp $fH',
          points: [l, h],
          intervalNotation: '(-∞, $fL$b1 ∪ $b2$fH, ∞)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      title: 'Original Inequality',
      explanation: 'Start with the absolute value inequality.',
      latex: input.trim(),
    ));

    final innerStr = '${_coef(p.a)}x ${p.b >= 0 ? "+ ${_fmt(p.b)}" : "- ${_fmt(p.b.abs())}"}';
    final kStr = _fmt(p.k);
    bool absOnLeft = p.absOnLeft;
    String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
    final isNarrow = effectiveOp == '<' || effectiveOp == '≤';

    if (isNarrow) {
      final nkStr = _fmt(-p.k);
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Apply |X| < k Property',
        explanation: 'Rewrite as a compound inequality.',
        latex: '$nkStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
      ));
    } else {
      final flipOp = _flipOp(effectiveOp);
      steps.add(StepModel(
        stepNumber: n++,
        title: 'Apply |X| > k Property',
        explanation: 'Split into two cases.',
        latex: '$innerStr ${_texOp(flipOp)} -$kStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
      ));
    }

    steps.add(StepModel(
      stepNumber: n++,
      title: 'Solution',
      explanation: 'The complete solution set.',
      latex: solve(input).intervalNotation ?? '',
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('²', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '≥')
        .replaceAll('<=', '≤');

    if (!s.contains('|')) return null;

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);

    bool absOnLeft;
    String absSide, constStr;
    if (left.contains('|')) {
      absSide = left; constStr = right; absOnLeft = true;
    } else if (right.contains('|')) {
      absSide = right; constStr = left; absOnLeft = false;
    } else {
      return null;
    }

    final inner = absSide.replaceAll('|', '');
    final k = double.tryParse(constStr);
    if (k == null) return null;

    final parsed = _parseLinear(inner);
    if (parsed == null) return null;

    return _Parsed(op: op, a: parsed['x']!, b: parsed['c']!, k: k, absOnLeft: absOnLeft);
  }

  static String? _extractOp(String s) {
    if (s.contains('≥')) return '≥';
    if (s.contains('≤')) return '≤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coef(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmt(a);
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _texOp(String op) {
    switch (op) {
      case '≥': return '\\geq';
      case '≤': return '\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }

  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '≥': return '≤';
      case '≤': return '≥';
      default: return op;
    }
  }

}

class _Parsed {
  final String op;
  final double a, b, k;
  final bool absOnLeft;
  const _Parsed({required this.op, required this.a, required this.b, required this.k, required this.absOnLeft});
}
