// AUTOGENERATED by yintercept_generator.py
class YIFraction {
  final int numerator;
  final int denominator;

  const YIFraction({required this.numerator, required this.denominator});

  bool get isWhole => denominator == 1;
  bool get isZero => numerator == 0;
  bool get isPositive => !isZero && numerator.sign == denominator.sign;
  bool get isNegative => !isZero && !isPositive;

  YIFraction simplified() {
    if (numerator == 0) return const YIFraction(numerator: 0, denominator: 1);
    int n = numerator, d = denominator;
    if (d < 0) { n = -n; d = -d; }
    if (d == 1) return YIFraction(numerator: n, denominator: 1);
    final g = _gcd(n.abs(), d);
    return g == 1 ? YIFraction(numerator: n, denominator: d)
                  : YIFraction(numerator: n ~/ g, denominator: d ~/ g);
  }

  YIFraction operator +(YIFraction o) => YIFraction(
    numerator: numerator * o.denominator + o.numerator * denominator,
    denominator: denominator * o.denominator,
  ).simplified();

  YIFraction operator -(YIFraction o) => YIFraction(
    numerator: numerator * o.denominator - o.numerator * denominator,
    denominator: denominator * o.denominator,
  ).simplified();

  YIFraction operator *(YIFraction o) {
    final g1 = _gcd(numerator.abs(), o.denominator.abs());
    final g2 = _gcd(o.numerator.abs(), denominator.abs());
    return YIFraction(
      numerator: (numerator ~/ g1) * (o.numerator ~/ g2),
      denominator: (denominator ~/ g2) * (o.denominator ~/ g1),
    ).simplified();
  }

  YIFraction operator /(YIFraction o) => this * o.reciprocal();
  YIFraction divided(YIFraction o) => this / o;
  YIFraction operator -() => YIFraction(numerator: -numerator, denominator: denominator);

  YIFraction abs() => YIFraction(numerator: numerator.abs(), denominator: denominator);

  YIFraction reciprocal() {
    if (numerator == 0) throw StateError('Reciprocal of zero');
    return YIFraction(numerator: denominator, denominator: numerator).simplified();
  }

  double toDouble() => numerator / denominator;

  factory YIFraction.fromDouble(double v) {
    if (v == v.truncateToDouble()) return YIFraction(numerator: v.toInt(), denominator: 1);
    final s = (v * 1000).round();
    return YIFraction(numerator: s, denominator: 1000).simplified();
  }

  int compareTo(YIFraction o) => (numerator * o.denominator).compareTo(o.numerator * denominator);
  bool operator <(YIFraction o) => compareTo(o) < 0;
  bool operator >(YIFraction o) => compareTo(o) > 0;
  bool operator <=(YIFraction o) => compareTo(o) <= 0;
  bool operator >=(YIFraction o) => compareTo(o) >= 0;

  @override
  bool operator ==(Object other) =>
      other is YIFraction && numerator * other.denominator == other.numerator * denominator;

  @override
  int get hashCode => Object.hash(numerator, denominator);

  @override
  String toString() => denominator == 1 ? '$numerator' : '$numerator/$denominator';

  static int _gcd(int a, int b) {
    while (b != 0) { final t = b; b = a % b; a = t; }
    return a;
  }
}
