// AUTOGENERATED by yintercept_generator.py
import 'dart:math';
import 'fraction.dart';
import 'yi_steps.dart';

// ── Constants ────────────────────────────────────────────────────────

const zeroFrac = YIFraction(numerator: 0, denominator: 1);
const oneFrac = YIFraction(numerator: 1, denominator: 1);
const negOneFrac = YIFraction(numerator: -1, denominator: 1);

// ── LaTeX Helpers ────────────────────────────────────────────────────

String fracLatex(YIFraction f) {
  final s = f.simplified();
  if (s.denominator == 1) return '${s.numerator}';
  return s.numerator < 0
      ? '-\\frac{${s.numerator.abs()}}{${s.denominator}}'
      : '\\frac{${s.numerator}}{${s.denominator}}';
}

String boxLatex(String inner) => '\\boxed{$inner}';

String textLatex(String t) {
  return '\\text{${t.replaceAll('{', r'\{').replaceAll('}', r'\}').replaceAll(r'\', r'\\').replaceAll('%', r'\%')}}';
}

String mxLatex(YIFraction m) {
  final s = m.simplified();
  if (s == oneFrac) return 'x';
  if (s == negOneFrac) return '-x';
  return '${fracLatex(s)}x';
}

String eqLatex(YIFraction m, YIFraction b) {
  final ms = m.simplified(), bs = b.simplified();
  if (ms.isZero) return 'y = ${fracLatex(bs)}';
  final mp = mxLatex(ms);
  if (bs.isZero) return 'y = $mp';
  return bs.numerator > 0 ? 'y = $mp + ${fracLatex(bs)}' : 'y = $mp - ${fracLatex(bs.abs())}';
}

String sfLatex(int A, int B, int C) {
  String t(int c, String v, bool first) {
    if (c == 0) return '';
    final a = c.abs(), vs = a == 1 ? v : '$a$v';
    if (first) return c < 0 ? '-$vs' : vs;
    return c < 0 ? '- $vs' : '+ $vs';
  }
  return '${t(A, 'x', true)} ${t(B, 'y', false)} = $C'.trim();
}

String gfLatex(int A, int B, int C) {
  String t(int c, String v, bool first) {
    if (c == 0) return '';
    final a = c.abs(), vs = a == 1 ? v : '$a$v';
    if (first) return c < 0 ? '-$vs' : vs;
    return c < 0 ? '- $vs' : '+ $vs';
  }
  final xp = t(A, 'x', true), yp = t(B, 'y', false);
  final cp = C > 0 ? '+ $C' : C < 0 ? '- ${C.abs()}' : '';
  return '${[xp, yp, cp].where((s) => s.isNotEmpty).join(' ')} = 0';
}

String termLatex(int c, String v, {required bool isFirst}) {
  if (c == 0) return '';
  final a = c.abs(), vs = a == 1 ? v : '$a$v';
  return isFirst ? (c < 0 ? '-$vs' : vs) : (c < 0 ? '- $vs' : '+ $vs');
}

String termStr(int c, String v, {required bool isFirst}) => termLatex(c, v, isFirst: isFirst);

String rhsAfterMovingXLatex(int A, int B, int C) {
  final y = B == 1 ? 'y' : B == -1 ? '-y' : '${B}y';
  return '$y = $C ${A > 0 ? '-' : '+'} ${A.abs() == 1 ? 'x' : '${A.abs()}x'}';
}

String direction(double m) =>
    m > 0 ? 'Rising \u2197' : m < 0 ? 'Falling \u2198' : 'Horizontal \u2192';

String riseRun(YIFraction m) {
  final s = m.simplified();
  return s.denominator == 1 ? '${s.numerator} / 1' : '${s.numerator} / ${s.denominator}';
}

// ── Form Conversion Helpers ─────────────────────────────────────────

int lcm(int a, int b) => a == 0 || b == 0 ? 1 : (a * b).abs() ~/ _gcd2(a.abs(), b.abs());

int _gcd2(int a, int b) { while (b != 0) { final t = b; b = a % b; a = t; } return a; }

int gcd3(int a, int b, int c) => _gcd2(_gcd2(a, b), c);

String sfString(int A, int B, int C) {
  final x = termStr(A, 'x', isFirst: true);
  final y = termStr(B, 'y', isFirst: false);
  return '$x $y = $C'.replaceAll('  ', ' ').trim();
}

String gfString(int A, int B, int C) {
  final xp = termStr(A, 'x', isFirst: true);
  final yp = termStr(B, 'y', isFirst: false);
  final cp = C > 0 ? '+ $C' : C < 0 ? '- ${C.abs()}' : '';
  return '${[xp, yp, cp].where((s) => s.isNotEmpty).join(' ')} = 0';
}

String generalFormFromABC(int A, int B, int C) => gfString(A, B, -C);

String standardFormFromSlopeIntercept(YIFraction m, YIFraction b) {
  if (m.isZero) return 'y = ${fracLatex(b)}';
  final s = lcm(m.denominator, b.denominator);
  final A = -(m.numerator * (s ~/ m.denominator));
  final C = b.numerator * (s ~/ b.denominator);
  final g = gcd3(A.abs(), s, C.abs());
  return sfString(A ~/ g, s ~/ g, C ~/ g);
}

String generalFormFromSlopeIntercept(YIFraction m, YIFraction b) {
  if (m.isZero) {
    final nb = -b.numerator;
    return b.denominator == 1
        ? 'y ${nb >= 0 ? '+ $nb' : '- ${nb.abs()}'} = 0'
        : 'y + ${YIFraction(numerator: nb, denominator: b.denominator).simplified()} = 0';
  }
  final s = lcm(m.denominator, b.denominator);
  final A = -(m.numerator * (s ~/ m.denominator));
  final C = -(b.numerator * (s ~/ b.denominator));
  final g = gcd3(A.abs(), s, C.abs());
  return gfString(A ~/ g, s ~/ g, C ~/ g);
}

String sfTexFromSlopeIntercept(YIFraction m, YIFraction b) {
  if (m.isZero) return 'y = ${fracLatex(b)}';
  final s = lcm(m.denominator, b.denominator);
  final A = -(m.numerator * (s ~/ m.denominator));
  final C = b.numerator * (s ~/ b.denominator);
  final g = gcd3(A.abs(), s, C.abs());
  return sfLatex(A ~/ g, s ~/ g, C ~/ g);
}

String gfTexFromSlopeIntercept(YIFraction m, YIFraction b) {
  if (m.isZero) {
    final nb = -b.numerator;
    return 'y ${nb >= 0 ? '+' : '-'} ${nb.abs()} = 0';
  }
  final s = lcm(m.denominator, b.denominator);
  final A = -(m.numerator * (s ~/ m.denominator));
  final C = -(b.numerator * (s ~/ b.denominator));
  final g = gcd3(A.abs(), s, C.abs());
  return gfLatex(A ~/ g, s ~/ g, C ~/ g);
}

// ── Fraction Parser ──────────────────────────────────────────────────

YIFraction? parseFractionString(String text) {
  text = text.trim().replaceAll('\u2212', '-');
  if (text.contains('/')) {
    if (text.contains(' ')) {
      final p = text.split(' ');
      if (p.length == 2) {
        final w = int.tryParse(p[0]), fp = p[1].split('/');
        if (w != null && fp.length == 2) {
          final n = int.tryParse(fp[0]), d = int.tryParse(fp[1]);
          if (n != null && d != null && d != 0)
            return YIFraction(numerator: (w.abs() * d + n) * (w < 0 ? -1 : 1), denominator: d).simplified();
        }
      }
    }
    final p = text.split('/');
    if (p.length == 2) {
      final n = int.tryParse(p[0]), d = int.tryParse(p[1]);
      if (n != null && d != null && d != 0) return YIFraction(numerator: n, denominator: d).simplified();
    }
  }
  final iv = int.tryParse(text);
  if (iv != null) return YIFraction(numerator: iv, denominator: 1);
  final dv = double.tryParse(text);
  return dv != null ? YIFraction.fromDouble(dv) : null;
}

// ── Result Models ────────────────────────────────────────────────────

enum YIInputType { slopeIntercept, standardForm, generalForm, jumbled }

class YIResult {
  final YIFraction? yIntercept;
  final YIFraction? xIntercept;
  final String generalForm;
  final String standardForm;
  final YIFraction? slope;
  final String equation;
  final String direction;
  final String angle;
  final String riseRun;
  final YIInputType inputType;
  final List<YISolverStep> slopeStepsFromStandard;
  final List<YISolverStep> slopeStepsFromGeneral;
  final List<YISolverStep> xInterceptSteps;
  final List<YISolverStep> standardFormSteps;
  final List<YISolverStep> generalFormSteps;

  const YIResult({
    required this.yIntercept, required this.xIntercept,
    required this.generalForm, required this.standardForm,
    required this.slope, required this.equation,
    required this.direction, required this.angle, required this.riseRun,
    required this.inputType,
    required this.slopeStepsFromStandard, required this.slopeStepsFromGeneral,
    required this.xInterceptSteps,
    required this.standardFormSteps, required this.generalFormSteps,
  });
}

// ── Parallel/Perpendicular Models ────────────────────────────────────

enum PPRelationship { parallel, perpendicular, neither, sameLine }

class PPResult {
  final YIFraction? slope1, slope2, yIntercept1, yIntercept2;
  final String slopeIntercept1, slopeIntercept2;
  final PPRelationship relationship;
  final String verdict, verdictSymbol;
  final List<PPSolverStep> steps;
  final int a1, b1, c1, a2, b2, c2;

  const PPResult({
    required this.slope1, required this.slope2,
    required this.yIntercept1, required this.yIntercept2,
    required this.slopeIntercept1, required this.slopeIntercept2,
    required this.relationship, required this.verdict, required this.verdictSymbol,
    required this.steps,
    required this.a1, required this.b1, required this.c1,
    required this.a2, required this.b2, required this.c2,
  });
}

// ── Internal Parser Types ────────────────────────────────────────────

class _Term {
  final String variable;
  final YIFraction coeff;
  const _Term({required this.variable, required this.coeff});
}

class _Line {
  final int A, B, C;
  final String display;
  const _Line({required this.A, required this.B, required this.C, required this.display});
}

class _SIResult {
  final YIFraction? slope, yInt;
  final String equation, latexEquation;
  final bool isVertical;
  const _SIResult({
    required this.slope, required this.yInt,
    required this.equation, required this.latexEquation,
    required this.isVertical,
  });
}

// ═══════════════════════════════════════════════════════════════════════
// Y-INTERCEPT SOLVER
// ═══════════════════════════════════════════════════════════════════════

class YInterceptSolver {
  YInterceptSolver._();

  // ── Public API ─────────────────────────────────────────────────────

  static YIResult? tryParseAny(String input) {
    final p = _parseAnyForm(input);
    if (p == null) return null;
    final (a, b, c, type) = p;
    return _computeFromABC(a, b, c, type);
  }

  static YIResult? tryParseSlopeIntercept({required String mText, required String bText}) {
    final m = parseFractionString(mText);
    final b = parseFractionString(bText);
    if (m == null || b == null) return null;
    return _computeSlopeIntercept(m.simplified(), b.simplified());
  }

  static YIResult fromSlopeIntercept({required YIFraction m, required YIFraction b}) =>
      _computeSlopeIntercept(m.simplified(), b.simplified());

  static YIResult fromSlopeInterceptDoubles({required double m, required double b}) =>
      _computeSlopeIntercept(YIFraction.fromDouble(m), YIFraction.fromDouble(b));

  static YIResult fromStandardForm({required int A, required int B, required int C}) =>
      _computeFromABC(A, B, C, YIInputType.standardForm);

  // ── Universal Parser ──────────────────────────────────────────────

  static (int, int, int, YIInputType)? _parseAnyForm(String raw) {
    String s = raw.replaceAll('\u2212', '-').replaceAll(' ', '');
    final eqIdx = s.indexOf('=');
    if (eqIdx < 0) return null;
    final lhs = s.substring(0, eqIdx), rhs = s.substring(eqIdx + 1);

    YIFraction lA = zeroFrac, lB = zeroFrac, lC = zeroFrac;
    for (final t in _tokenise(lhs)) {
      if (t.variable == 'x') lA += t.coeff;
      else if (t.variable == 'y') lB += t.coeff;
      else lC += t.coeff;
    }
    YIFraction rA = zeroFrac, rB = zeroFrac, rC = zeroFrac;
    for (final t in _tokenise(rhs)) {
      if (t.variable == 'x') rA += t.coeff;
      else if (t.variable == 'y') rB += t.coeff;
      else rC += t.coeff;
    }

    final A = lA - rA, B = lB - rB, C = rC - lC;
    final denom = lcm(lcm(A.denominator, B.denominator), C.denominator);
    final iA = A.numerator * (denom ~/ A.denominator);
    final iB = B.numerator * (denom ~/ B.denominator);
    final iC = C.numerator * (denom ~/ C.denominator);

    final g = gcd3(iA.abs(), iB.abs(), iC.abs());
    return (g == 0 ? iA : iA ~/ g, g == 0 ? iB : iB ~/ g, g == 0 ? iC : iC ~/ g,
            _detectInputType(raw, A.numerator, B.numerator, C.numerator));
  }

  static List<_Term> _tokenise(String expr) {
    if (expr.isEmpty) return [];
    if (!expr.startsWith('-') && !expr.startsWith('+')) expr = '+$expr';
    final tokens = <String>[];
    for (int i = 1, s = 0; i <= expr.length; i++) {
      if (i == expr.length || expr[i] == '+' || expr[i] == '-') {
        tokens.add(expr.substring(s, i).trim());
        s = i;
      }
    }
    return tokens.map((t) => _parseTerm(t)).whereType<_Term>().toList();
  }

  static _Term? _parseTerm(String tok) {
    tok = tok.trim();
    if (tok.isEmpty) return null;
    int sign = 1;
    if (tok.startsWith('-')) { sign = -1; tok = tok.substring(1).trim(); }
    else if (tok.startsWith('+')) { tok = tok.substring(1).trim(); }

    final hasX = tok.toLowerCase().contains('x');
    final hasY = tok.toLowerCase().contains('y');
    if (hasX && hasY) return null;

    String varName = 'const', coeffStr = tok;
    if (hasX) { varName = 'x'; coeffStr = tok.toLowerCase().replaceAll('x', '').replaceAll('*', '').trim(); }
    else if (hasY) { varName = 'y'; coeffStr = tok.toLowerCase().replaceAll('y', '').replaceAll('*', '').trim(); }

    YIFraction coeff;
    if (coeffStr.isEmpty) {
      coeff = oneFrac;
    } else if (coeffStr.contains('/')) {
      final p = coeffStr.split('/');
      if (p.length != 2) return null;
      final n = int.tryParse(p[0].trim()), d = int.tryParse(p[1].trim());
      if (n == null || d == null || d == 0) return null;
      coeff = YIFraction(numerator: n, denominator: d).simplified();
    } else {
      final n = int.tryParse(coeffStr);
      if (n != null) { coeff = YIFraction(numerator: n, denominator: 1); }
      else { final d = double.tryParse(coeffStr); if (d == null) return null; coeff = YIFraction.fromDouble(d); }
    }

    return _Term(
      variable: varName,
      coeff: YIFraction(numerator: sign * coeff.numerator, denominator: coeff.denominator).simplified(),
    );
  }

  static YIInputType _detectInputType(String raw, int A, int B, int C) {
    final s = raw.replaceAll(' ', '').toLowerCase();
    if (s.endsWith('=0')) return YIInputType.generalForm;
    if (s.startsWith('y=')) return YIInputType.slopeIntercept;
    return YIInputType.standardForm;
  }

  // ── Core Computation ──────────────────────────────────────────────

  static YIResult _computeFromABC(int A, int B, int C, YIInputType type) {
    final sfStr = sfString(A, B, C), gfStr = generalFormFromABC(A, B, C);
    final sfTex = sfLatex(A, B, C), gfTex = gfLatex(A, B, -C);

    if (B == 0) {
      if (A == 0) return YIResult(
        yIntercept: null, xIntercept: null,
        generalForm: gfStr, standardForm: sfStr, slope: null,
        equation: C == 0 ? 'All real numbers' : 'No solution',
        direction: 'N/A', angle: 'N/A', riseRun: 'N/A', inputType: type,
        slopeStepsFromStandard: const [], slopeStepsFromGeneral: const [],
        xInterceptSteps: const [], standardFormSteps: const [], generalFormSteps: const [],
      );
      final xVal = YIFraction(numerator: C, denominator: A).simplified();
      return YIResult(
        yIntercept: null, xIntercept: xVal,
        generalForm: gfStr, standardForm: sfStr, slope: null,
        equation: 'x = $xVal', direction: 'Vertical |', angle: '90.0\u00b0',
        riseRun: 'Undefined', inputType: type,
        slopeStepsFromStandard: buildVerticalSlopeSteps(A, C, sfTex, gfTex),
        slopeStepsFromGeneral: buildVerticalSlopeSteps(A, C, sfTex, gfTex),
        xInterceptSteps: buildVerticalXSteps(A, C, xVal),
        standardFormSteps: [], generalFormSteps: [],
      );
    }

    final m = YIFraction(numerator: -A, denominator: B).simplified();
    final b = YIFraction(numerator: C, denominator: B).simplified();
    final eqTex = eqLatex(m, b);
    final xInt = m.isZero ? null : (b * negOneFrac).divided(m).simplified();
    final angleVal = atan(m.toDouble()) * 180 / pi;

    return YIResult(
      yIntercept: b, xIntercept: xInt,
      generalForm: gfStr, standardForm: sfStr, slope: m, equation: eqTex,
      direction: direction(m.toDouble()),
      angle: '${angleVal.toStringAsFixed(1)}\u00b0',
      riseRun: riseRun(m), inputType: type,
      slopeStepsFromStandard: buildSlopeStepsFromStandard(A, B, C, m, b, sfTex, gfTex, eqTex),
      slopeStepsFromGeneral: buildSlopeStepsFromGeneral(A, B, C, m, b, sfTex, gfTex, eqTex),
      xInterceptSteps: buildXInterceptSteps(m, b, xInt),
      standardFormSteps: buildStandardFormSteps(A, B, C, gfTex, sfTex),
      generalFormSteps: buildGeneralFormSteps(A, B, C, sfTex, gfTex),
    );
  }

  static YIResult _computeSlopeIntercept(YIFraction m, YIFraction b) {
    final ms = m.simplified(), bs = b.simplified();
    final eqTex = eqLatex(ms, bs);
    final sfStr = standardFormFromSlopeIntercept(ms, bs);
    final gfStr = generalFormFromSlopeIntercept(ms, bs);
    final sfTex = sfTexFromSlopeIntercept(ms, bs);
    final gfTex = gfTexFromSlopeIntercept(ms, bs);
    final xInt = ms.isZero ? null : (bs * negOneFrac).divided(ms).simplified();
    final angleVal = atan(ms.toDouble()) * 180 / pi;

    return YIResult(
      yIntercept: bs, xIntercept: xInt,
      generalForm: gfStr, standardForm: sfStr,
      slope: ms, equation: eqTex,
      direction: direction(ms.toDouble()),
      angle: '${angleVal.toStringAsFixed(1)}\u00b0',
      riseRun: riseRun(ms), inputType: YIInputType.slopeIntercept,
      slopeStepsFromStandard: buildSlopeInterceptDirectSteps(ms, bs, eqTex, sfTex, gfTex),
      slopeStepsFromGeneral: buildSlopeInterceptDirectSteps(ms, bs, eqTex, sfTex, gfTex),
      xInterceptSteps: buildXInterceptSteps(ms, bs, xInt),
      standardFormSteps: buildStandardFormFromSlopeInterceptSteps(ms, bs, sfTex, gfTex),
      generalFormSteps: buildGeneralFormFromSlopeInterceptSteps(ms, bs, sfTex, gfTex),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// PARALLEL / PERPENDICULAR SOLVER
// ═══════════════════════════════════════════════════════════════════════

class ParallelPerpendicularSolver {
  ParallelPerpendicularSolver._();

  static PPResult? tryParse({required String line1, required String line2}) {
    final l1 = _parseLine(line1), l2 = _parseLine(line2);
    if (l1 == null || l2 == null) return null;
    return _compute(l1, l2);
  }

  static _Line? _parseLine(String raw) {
    final s = raw.replaceAll('\u2212', '-').replaceAll(' ', '').toLowerCase();
    final eqIdx = s.indexOf('=');
    if (eqIdx < 0) return null;
    int A = 0, B = 0, C = 0;

    void add(String expr, int sign) {
      final e = expr.isEmpty ? '' : (expr[0] != '-' ? '+$expr' : expr);
      final re = RegExp(r'[+\-][^+\-]+');
      for (final m in re.allMatches(e)) {
        final tok = m.group(0)!;
        final tokSign = tok[0] == '-' ? -1 : 1;
        final body = tok.substring(1);
        if (body.contains('x')) A += sign * tokSign * _coeff(body.replaceAll('x', ''));
        else if (body.contains('y')) B += sign * tokSign * _coeff(body.replaceAll('y', ''));
        else { final v = int.tryParse(body); if (v == null) return; C += sign * tokSign * v; }
      }
    }

    add(s.substring(0, eqIdx), 1);
    add(s.substring(eqIdx + 1), -1);
    if (A == 0 && B == 0) return null;
    return _Line(A: A, B: B, C: C, display: '${A}x + ${B}y + $C = 0');
  }

  static int _coeff(String raw) {
    if (raw.isEmpty || raw == '+') return 1;
    if (raw == '-') return -1;
    return int.tryParse(raw) ?? 1;
  }

  static _SIResult _toSI(_Line l) {
    if (l.B == 0) {
      final xv = YIFraction(numerator: -l.C, denominator: l.A).simplified();
      return _SIResult(slope: null, yInt: null, equation: 'x = $xv',
          latexEquation: 'x = ${fracLatex(xv)}', isVertical: true);
    }
    final m = YIFraction(numerator: -l.A, denominator: l.B).simplified();
    final b = YIFraction(numerator: -l.C, denominator: l.B).simplified();
    return _SIResult(slope: m, yInt: b, equation: _siStr(m, b),
        latexEquation: _siLatex(m, b), isVertical: false);
  }

  static String _siStr(YIFraction m, YIFraction b) {
    if (m.isZero) return 'y = $b';
    final mp = m == oneFrac ? 'x' : m == negOneFrac ? '-x' : '${m}x';
    if (b.isZero) return 'y = $mp';
    return b.numerator > 0 ? 'y = $mp + $b' : 'y = $mp - ${b.abs()}';
  }

  static String _siLatex(YIFraction m, YIFraction b) {
    if (m.isZero) return 'y = ${fracLatex(b)}';
    final mp = m == oneFrac ? 'x' : m == negOneFrac ? '-x' : '${fracLatex(m)}x';
    if (b.isZero) return 'y = $mp';
    return b.numerator > 0 ? 'y = $mp + ${fracLatex(b)}' : 'y = $mp - ${fracLatex(b.abs())}';
  }

  static PPRelationship _classify(_SIResult s1, _SIResult s2) {
    if (s1.isVertical && s2.isVertical) return s1.equation == s2.equation ? PPRelationship.sameLine : PPRelationship.parallel;
    if (s1.isVertical || s2.isVertical) return PPRelationship.neither;
    final m1 = s1.slope!, m2 = s2.slope!;
    if (m1 == m2) return (s1.yInt != null && s2.yInt != null && s1.yInt == s2.yInt) ? PPRelationship.sameLine : PPRelationship.parallel;
    return (m1 * m2).simplified().numerator == -(m1 * m2).simplified().denominator ? PPRelationship.perpendicular : PPRelationship.neither;
  }

  // ── Computation + Step Building ───────────────────────────────────

  static PPResult _compute(_Line l1, _Line l2) {
    final steps = <PPSolverStep>[];
    final si1 = _toSI(l1), si2 = _toSI(l2);
    final m1Str = si1.slope == null ? 'undefined' : fracLatex(si1.slope!);
    final m2Str = si2.slope == null ? 'undefined' : fracLatex(si2.slope!);
    final rel = _classify(si1, si2);
    final vStr = _verdictString(rel), vSym = _verdictSymbol(rel);

    String lineToLatex(_Line l) => '${l.A}x ${l.B >= 0 ? '+' : '-'} ${l.B.abs()}y ${l.C >= 0 ? '+' : '-'} ${l.C.abs()} = 0';

    // Step 1: Identify lines
    steps.add(PPSolverStep(number: 1, title: 'Identify the equations', blocks: [
      const PPStepBlock(type: PPBlockType.note, content: 'Rewrite each equation in general form to identify A, B, C.'),
      const PPStepBlock(type: PPBlockType.formula, latex: r'Ax + By + C = 0', label: 'General form'),
      PPStepBlock(type: PPBlockType.substitution, label: 'Line 1', latex: '${lineToLatex(l1)} \\Rightarrow A_1=${l1.A}, B_1=${l1.B}, C_1=${l1.C}'),
      PPStepBlock(type: PPBlockType.substitution, label: 'Line 2', latex: '${lineToLatex(l2)} \\Rightarrow A_2=${l2.A}, B_2=${l2.B}, C_2=${l2.C}'),
    ]));

    // Step 2-3: Convert to slope-intercept
    steps.addAll(_buildSISteps(l1, si1, l2, si2));

    // Step: Compare slopes
    steps.add(PPSolverStep(number: 3, title: 'Extract and compare slopes', blocks: [
      const PPStepBlock(type: PPBlockType.note, content: 'The slope is the coefficient of x after isolating y.'),
      const PPStepBlock(type: PPBlockType.formula, latex: r'y = mx + b \quad\Rightarrow\quad \text{slope} = m'),
      PPStepBlock(type: PPBlockType.substitution, label: 'Line 1', latex: '${si1.latexEquation} \\Rightarrow m_1 = $m1Str'),
      PPStepBlock(type: PPBlockType.substitution, label: 'Line 2', latex: '${si2.latexEquation} \\Rightarrow m_2 = $m2Str'),
      PPStepBlock(type: PPBlockType.result, latex: 'm_1 = $m1Str \\qquad m_2 = $m2Str'),
    ]));

    // Step: Relationship test + conclusion
    steps.addAll(_buildTestAndConclusion(rel, si1, si2, m1Str, m2Str));

    return PPResult(
      slope1: si1.slope, slope2: si2.slope,
      yIntercept1: si1.yInt, yIntercept2: si2.yInt,
      slopeIntercept1: si1.equation, slopeIntercept2: si2.equation,
      relationship: rel, verdict: vStr, verdictSymbol: vSym,
      steps: steps,
      a1: l1.A, b1: l1.B, c1: l1.C,
      a2: l2.A, b2: l2.B, c2: l2.C,
    );
  }

  static List<PPSolverStep> _buildSISteps(_Line l1, _SIResult si1, _Line l2, _SIResult si2) {
    PPSolverStep one(_Line l, _SIResult si, int num, String label) {
      if (l.B == 0) {
        return PPSolverStep(number: num, title: 'Convert $label to slope-intercept', groupKey: 'si',
          blocks: [
            PPStepBlock(type: PPBlockType.note, content: 'B=0, no y-term. Vertical line with undefined slope.'),
            const PPStepBlock(type: PPBlockType.formula, latex: r'B = 0 \;\Rightarrow\; Ax + C = 0 \;\Rightarrow\; x = -\tfrac{C}{A}', label: 'Vertical line rule'),
            PPStepBlock(type: PPBlockType.substitution, latex: '${l.A}x + (${l.C}) = 0 \\\\[4pt] ${l.A}x = ${-l.C} \\\\[4pt] x = \\dfrac{${-l.C}}{${l.A}}'),
            PPStepBlock(type: PPBlockType.result, latex: si.latexEquation, content: '${si.equation}'),
          ]);
      }
      final mFrac = YIFraction(numerator: -l.A, denominator: l.B).simplified();
      final bFrac = YIFraction(numerator: -l.C, denominator: l.B).simplified();
      return PPSolverStep(number: num, title: 'Convert $label to slope-intercept', groupKey: 'si',
        blocks: [
          PPStepBlock(type: PPBlockType.note, content: 'Isolate y, then divide every term by B=${l.B}.'),
          const PPStepBlock(type: PPBlockType.formula, latex: r'Ax + By + C = 0 \;\Rightarrow\; y = -\dfrac{A}{B}x - \dfrac{C}{B}', label: 'Formula'),
          PPStepBlock(type: PPBlockType.substitution, latex: '${l.A}x + ${l.B}y + ${l.C} = 0 \\\\[4pt] ${l.B}y = ${-l.A}x + ${-l.C} \\\\[4pt] y = \\dfrac{${-l.A}}{${l.B}}x + \\dfrac{${-l.C}}{${l.B}}'),
          PPStepBlock(type: PPBlockType.working, latex: 'm = ${fracLatex(mFrac)} \\\\[4pt] b = ${fracLatex(bFrac)}'),
          PPStepBlock(type: PPBlockType.result, latex: si.latexEquation, content: si.equation),
        ]);
    }
    return [one(l1, si1, 2, 'Line 1'), one(l2, si2, 2, 'Line 2')];
  }

  static List<PPSolverStep> _buildTestAndConclusion(
    PPRelationship rel, _SIResult si1, _SIResult si2, String m1Str, String m2Str,
  ) {
    final m1T = si1.slope != null ? fracLatex(si1.slope!) : r'\text{undefined}';
    final m2T = si2.slope != null ? fracLatex(si2.slope!) : r'\text{undefined}';

    PPSolverStep testStep(int n, String title, List<PPStepBlock> blocks) =>
        PPSolverStep(number: n, title: title, blocks: blocks);

    final steps = <PPSolverStep>[];

    if (rel == PPRelationship.parallel) {
      final b1T = si1.yInt != null ? fracLatex(si1.yInt!) : '---';
      final b2T = si2.yInt != null ? fracLatex(si2.yInt!) : '---';
      steps.add(testStep(4, 'Apply parallel test', [
        const PPStepBlock(type: PPBlockType.note, content: 'Parallel lines have equal slopes but different y-intercepts.'),
        const PPStepBlock(type: PPBlockType.formula, latex: r'm_1 = m_2 \quad\text{and}\quad b_1 \neq b_2', label: 'Condition'),
        PPStepBlock(type: PPBlockType.substitution, latex: 'm_1 = $m1T = m_2 \\;\\checkmark \\\\[4pt] b_1 = $b1T \\neq b_2 = $b2T \\;\\checkmark'),
        const PPStepBlock(type: PPBlockType.result, latex: r'\text{Lines are } \textbf{PARALLEL} \;(\parallel)'),
      ]));
    } else if (rel == PPRelationship.perpendicular) {
      final product = (si1.slope! * si2.slope!).simplified();
      steps.add(testStep(4, 'Apply perpendicular test', [
        const PPStepBlock(type: PPBlockType.note, content: 'Perpendicular lines have slopes whose product is -1.'),
        const PPStepBlock(type: PPBlockType.formula, latex: r'm_1 \times m_2 = -1', label: 'Condition'),
        PPStepBlock(type: PPBlockType.substitution, latex: '($m1T) \\times ($m2T) = ${fracLatex(product)} = -1 \\;\\checkmark'),
        const PPStepBlock(type: PPBlockType.result, latex: r'\text{Lines are } \textbf{PERPENDICULAR} \;(\perp)'),
      ]));
    } else if (rel == PPRelationship.sameLine) {
      steps.add(testStep(4, 'Apply coincident test', [
        const PPStepBlock(type: PPBlockType.note, content: 'Same slopes AND same y-intercepts means the lines are identical.'),
        const PPStepBlock(type: PPBlockType.formula, latex: r'm_1 = m_2 \quad\text{and}\quad b_1 = b_2', label: 'Condition'),
        PPStepBlock(type: PPBlockType.substitution, latex: 'm_1 = $m1T = m_2 \\;\\checkmark \\\\[4pt] b_1 = b_2 \\;\\checkmark'),
        const PPStepBlock(type: PPBlockType.result, latex: r'\text{Lines are the } \textbf{SAME LINE} \;(\equiv)'),
      ]));
    } else {
      final product = si1.slope != null && si2.slope != null
          ? (si1.slope! * si2.slope!).simplified() : null;
      final pT = product != null ? fracLatex(product) : 'undefined';
      steps.add(testStep(4, 'Apply both tests', [
        const PPStepBlock(type: PPBlockType.note, content: 'Check if slopes are equal (parallel) or product = -1 (perpendicular).'),
        const PPStepBlock(type: PPBlockType.formula, latex: r'\text{Parallel: } m_1 = m_2 \qquad \text{Perp: } m_1 \times m_2 = -1'),
        PPStepBlock(type: PPBlockType.substitution, latex: 'm_1 = $m1T, m_2 = $m2T'),
        PPStepBlock(type: PPBlockType.working, latex: '\\text{Parallel? } $m1T \\neq $m2T \\;\\times \\\\[4pt] \\text{Perp? } $m1T \\times $m2T = $pT \\neq -1 \\;\\times'),
        const PPStepBlock(type: PPBlockType.result, latex: r'\text{Lines are } \textbf{NEITHER}'),
      ]));
    }

    // Conclusion
    steps.add(PPSolverStep(number: 5, title: 'Conclusion', blocks: [
      PPStepBlock(type: PPBlockType.note, content: _verdictExplanation(rel)),
      PPStepBlock(type: PPBlockType.result,
          latex: '\\textbf{${_verdictSymbol(rel)}\\;\\text{Lines are ${_verdictString(rel).replaceAll(' ', '\\ ')}}}',
          content: '${_verdictSymbol(rel)} The lines are ${_verdictString(rel)}.'),
    ]));

    return steps;
  }

  static String _verdictString(PPRelationship r) {
    switch (r) {
      case PPRelationship.parallel: return 'Parallel';
      case PPRelationship.perpendicular: return 'Perpendicular';
      case PPRelationship.sameLine: return 'Same Line';
      case PPRelationship.neither: return 'Neither';
    }
  }

  static String _verdictSymbol(PPRelationship r) {
    switch (r) {
      case PPRelationship.parallel: return '\u2225';
      case PPRelationship.perpendicular: return '\u22a5';
      case PPRelationship.sameLine: return '\u2261';
      case PPRelationship.neither: return '\u2226';
    }
  }

  static String _verdictExplanation(PPRelationship r) {
    switch (r) {
      case PPRelationship.parallel: return 'Equal slopes, different y-intercepts. Lines never meet.';
      case PPRelationship.perpendicular: return 'Slopes are negative reciprocals (product = -1). Lines cross at 90\u00b0.';
      case PPRelationship.sameLine: return 'Both slopes and y-intercepts are identical. Lines overlap completely.';
      case PPRelationship.neither: return 'Neither condition is satisfied. Lines intersect at an oblique angle.';
    }
  }
}
