#!/usr/bin/env python3
"""
MathCalcu - Python Code Generator for Dart Math Solvers
Uses SymPy to verify correctness and generate Dart solver files.
All computation happens in generated Dart code at runtime (100% offline).
"""
import json, re, sys
from pathlib import Path
from sympy import (
    symbols, solve_univariate_inequality, oo, latex, sympify, sqrt,
    parse_expr, Interval, S, Poly, degree, LC, solve, factor, simplify
)

x = symbols("x")
PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = PROJECT_ROOT / "python_solvers" / "generated"
DART_LIB_DIR = PROJECT_ROOT / "lib" / "midterm" / "solvers" / "inequalities_solver"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
DART_LIB_DIR.mkdir(parents=True, exist_ok=True)

# Unicode chars used in Dart output
U_INFINITY = '\u221e'
U_INFINITY_LATEX = r'\infty'  # LaTeX infinity for raw Dart strings
U_INFINITY_LATEX_NR = '\\\\infty'  # LaTeX infinity for non-raw Dart strings (Dart: \\ → \)
U_EMPTY = '\u2205'
U_EMPTY_LATEX = r'\emptyset'  # LaTeX empty set for raw Dart strings
U_EMPTY_LATEX_NR = '\\\\emptyset'  # LaTeX empty set for non-raw Dart strings
U_UNION = '\u222a'
U_UNION_LATEX = r'\cup'  # LaTeX union for raw Dart strings
U_UNION_LATEX_NR = '\\\\cup'  # LaTeX union for non-raw Dart strings
U_SQUARED = '\u00b2'
U_GEQ = '\u2265'
U_LEQ = '\u2264'
U_DELTA = '\u0394'
U_CHECK = '\u2713'
U_TIMES = '\u00d7'

def to_latex(e):
    try: return latex(e)
    except: return str(e)

def write_json(fn, data):
    p = OUTPUT_DIR / fn
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"  + JSON: {p.name}")

def write_dart(fn, content):
    p = DART_LIB_DIR / fn
    content = re.sub(
        r"\s+title:\s*'[^']*',\s*\n\s+explanation:\s*'[^']*',\s*\n",
        "\n",
        content,
    )
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  + Dart: {p.name}")


# ─── SymPy Verification ────────────────────────────────────────────

def sympy_solve_inequality(expr_str):
    try:
        expr = parse_expr(expr_str)
        sol = solve_univariate_inequality(expr, x, relational=False)
        return sol
    except Exception as e:
        return None

def sympy_run_tests(solver_name, test_cases):
    """Run test cases through SymPy and report results."""
    print(f"\n  Verifying {solver_name} with SymPy...")
    for expr_str, expected_desc in test_cases:
        sol = sympy_solve_inequality(expr_str)
        status = "OK" if sol is not None else "FAIL"
        print(f"    {expr_str} -> {status} (expected: {expected_desc})")


# ─── Dart Code Templates ───────────────────────────────────────────

DART_HEADER = """// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';

"""

# Helper: format a double nicely with fraction support
FMT_COMMON = """
  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-{INF}' : '{INF}');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);
""".replace('{INF}', U_INFINITY)

FMT_TEXOP = """
  static String _texOp(String op) {
    switch (op) {
      case '{GEQ}': return '\\\\geq';
      case '{LEQ}': return '\\\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

FMT_FLIPOP = """
  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '{GEQ}': return '{LEQ}';
      case '{LEQ}': return '{GEQ}';
      default: return op;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

FMT_EVALOP = """
  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '{GEQ}': return left >= right;
      case '{LEQ}': return left <= right;
      default: return false;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

# LaTeX-compatible number formatter
FMT_COMMON_LATEX = """
  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-{INF}' : r'{INF}');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }
""".replace('{INF}', U_INFINITY_LATEX)

# LaTeX interval converter (converts plain-text intervals to LaTeX)
FMT_TOLATEX = """
  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\\u221e', r'{INF}')
        .replaceAll('\\u2205', r'{EMPTY}')
        .replaceAll('\\u222a', r'{UNION}');
  }
""".replace('{INF}', U_INFINITY_LATEX).replace('{EMPTY}', U_EMPTY_LATEX).replace('{UNION}', U_UNION_LATEX)

# LaTeX-compatible interval notation
FMT_INTERVAL_LATEX = """
  static String _intervalLatex(String op, double b) {
    final bs = _fmtLatex(b);
    switch (op) {
      case '>': return '($bs, {INF})';
      case '{GEQ}': return '[$bs, {INF})';
      case '<': return '(-{INF}, $bs)';
      case '{LEQ}': return '(-{INF}, $bs]';
      default: return '';
    }
  }
""".replace('{INF}', U_INFINITY_LATEX_NR).replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

# ─── LINEAR SOLVER ─────────────────────────────────────────────────

LINEAR_CODE = DART_HEADER + """
class GeneratedLinearSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');

      final a = p.a - p.ra;
      final b = p.b - p.rb;

      if (a == 0) {
        final sat = _evalOp(b, p.op, 0);
        return SolveResult(
          answer: sat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: sat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
        );
      }

      final boundary = -b / a;
      final finalOp = a < 0 ? _flipOp(p.op) : p.op;
      return SolveResult(
        answer: 'x $finalOp ${_fmt(boundary)}',
        points: [boundary],
        intervalNotation: _interval(finalOp, boundary),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final a = p.a - p.ra;
    final b = p.b - p.rb;

    if (p.ra != 0 || p.rb != 0) {
      final leftExpr = '${_coefLatex(p.a)}x ${p.b >= 0 ? "+ ${_fmtLatex(p.b)}" : "- ${_fmtLatex(p.b.abs())}"}';
      String rightMove = '';
      if (p.ra != 0) {
        rightMove += p.ra > 0 ? ' - ${_coefLatex(p.ra)}x' : ' + ${_coefLatex(-p.ra)}x';
      }
      if (p.rb != 0) {
        rightMove += p.rb > 0 ? ' - ${_fmtLatex(p.rb)}' : ' + ${_fmtLatex(-p.rb)}';
      }
      final intermediate = '$leftExpr$rightMove ${_texOp(p.op)} 0';
      final simplified = '${_coefLatex(a)}x ${b >= 0 ? "+ ${_fmtLatex(b)}" : "- ${_fmtLatex(b.abs())}"} ${_texOp(p.op)} 0';

      List<String> _parts = [];
      if (p.ra != 0) {
        final absRa = p.ra.abs();
        final term = absRa == 1 ? 'x' : '${_fmt(absRa)}x';
        _parts.add(p.ra > 0 ? 'subtract $term' : 'add $term');
      }
      if (p.rb != 0) {
        _parts.add(p.rb > 0 ? 'subtract ${_fmt(p.rb.abs())}' : 'add ${_fmt(p.rb.abs())}');
      }
      final hint = '${_parts.join(', ')} from both sides';

      List<String>? _moveDetails;
      if (p.rb != 0) {
        _moveDetails = [
          '${_fmtLatex(p.b)} ${p.rb > 0 ? "-" : "+"} ${_fmtLatex(p.rb.abs())} = ${_fmtLatex(b)}'
        ];
      }

      if (intermediate != simplified) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: hint,
          details: _moveDetails,
          latex: intermediate,
          subLatex: [simplified],
        ));
      } else {
        steps.add(StepModel(
          stepNumber: n++,
          hint: hint,
          details: _moveDetails,
          latex: simplified,
        ));
      }
    }

    if (a == 0) {
      final sat = _evalOp(b, p.op, 0);
      steps.add(StepModel(
        stepNumber: n++,
        hint: sat ? 'Always true — no x term remains' : 'Always false — no x term remains',
        latex: sat ? r'(-\infty, \infty)' : r'\emptyset',
      ));
      return steps;
    }

    if (b != 0) {
      final isoDetails = <String>[
        b > 0
          ? '${_coefLatex(a)}x + ${_fmtLatex(b)} - ${_fmtLatex(b)} ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} 0 - ${_fmtLatex(b)}'
          : '${_coefLatex(a)}x - ${_fmtLatex(-b)} + ${_fmtLatex(-b)} ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} 0 + ${_fmtLatex(-b)}',
        '${_coefLatex(a)}x ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b)}',
      ];
      steps.add(StepModel(
        stepNumber: n++,
        hint: b > 0 ? 'Subtract ${_fmt(b)} from both sides' : 'Add ${_fmt(-b)} to both sides',
        details: isoDetails,
        latex: '${_coefLatex(a)}x ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b)}',
      ));
    }

    if (a != 1 && a != -1) {
      final flip = a < 0;
      final divOp = flip ? _flipOp(p.op) : p.op;
      final divDetails = <String>[
        r'\\frac{' + '${_coefLatex(a)}x' + r'}{' + '${_fmtLatex(a)}' + r'} ' + '${_texOp(divOp)} ' + r'\\frac{' + '${_fmtLatex(-b)}' + r'}{' + '${_fmtLatex(a)}' + r'}',
        'x ${_texOp(divOp)} ${_fmtLatex(-b / a)}',
      ];
      if (flip) {
        divDetails.add(r'\\text{Dividing by }' + '${_fmt(a)}' + r'\\text{ flips }' + '${_texOp(p.op)}' + r'\\text{ to }' + '${_texOp(divOp)}');
      }
      steps.add(StepModel(
        stepNumber: n++,
        hint: flip ? 'Divide both sides by ${_fmt(a.abs())} and flip the inequality sign' : 'Divide both sides by ${_fmt(a)}',
        details: divDetails,
        latex: 'x ${_texOp(divOp)} ${_fmtLatex(-b / a)}',
      ));
    }

    final finalOp = a < 0 ? _flipOp(p.op) : p.op;
    steps.add(StepModel(
      stepNumber: n++,
      latex: _intervalLatex(finalOp, -b / a),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = _normalize(input);
    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);
    if (left.isEmpty || right.isEmpty) return null;

    final lp = _parseLinear(left);
    final rp = _parseLinear(right);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['x']!, b: lp['c']!,
      ra: rp['x']!, rb: rp['c']!,
    );
  }

  static String _normalize(String input) {
    return input
        .trim()
        .replaceAll('\\u2212', '-')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """')
        .replaceAll('=>', '""" + U_GEQ + """')
        .replaceAll('=<', '""" + U_LEQ + """')
        .replaceAll('x""" + U_SQUARED + """', 'x^2')
        .replaceAll('""" + U_SQUARED + """', '^2');
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TEXOP + FMT_FLIPOP + FMT_EVALOP + FMT_INTERVAL_LATEX + """

  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, """ + U_INFINITY + """)';
      case '""" + U_GEQ + """': return '[$bs, """ + U_INFINITY + """)';
      case '<': return '(-""" + U_INFINITY + """, $bs)';
      case '""" + U_LEQ + """': return '(-""" + U_INFINITY + """, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, ra, rb;
  const _Parsed({required this.op, required this.a, required this.b, required this.ra, required this.rb});
}
"""


# ─── QUADRATIC SOLVER ──────────────────────────────────────────────

QUAD_CODE = DART_HEADER + "import 'dart:math' as math;\n" + """
class GeneratedQuadraticSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');
      if (p.a == 0 && p.b == 0 && p.c == 0) {
        return SolveResult.error('Could not parse quadratic inequality.');
      }
      if (p.a == 0) return _solveLinear(p.b, p.c, p.op);

      final disc = p.b * p.b - 4 * p.a * p.c;

      if (disc < 0) {
        final allSat = p.a > 0
            ? (p.op == '>' || p.op == '""" + U_GEQ + """')
            : (p.op == '<' || p.op == '""" + U_LEQ + """');
        return SolveResult(
          answer: allSat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: allSat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
        );
      }

      final sqrtD = math.sqrt(disc);
      final r1 = (-p.b - sqrtD) / (2 * p.a);
      final r2 = (-p.b + sqrtD) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;

      if (disc == 0) {
        final root = -p.b / (2 * p.a);
        final opensUp = p.a > 0;
        if (opensUp) {
          if (p.op == '<') {
            return SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
          } else if (p.op == '""" + U_LEQ + """') {
            return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
          } else if (p.op == '>') {
            return SolveResult(answer: 'x < ${_fmt(root)} or x > ${_fmt(root)}', points: [root],
              intervalNotation: '(-""" + U_INFINITY + """, ${_fmt(root)}) """ + U_UNION + """ (${_fmt(root)}, """ + U_INFINITY + """)');
          } else {
            return SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
          }
        } else {
          if (p.op == '<') {
            return SolveResult(answer: 'x < ${_fmt(root)} or x > ${_fmt(root)}', points: [root],
              intervalNotation: '(-""" + U_INFINITY + """, ${_fmt(root)}) """ + U_UNION + """ (${_fmt(root)}, """ + U_INFINITY + """)');
          } else if (p.op == '""" + U_LEQ + """') {
            return SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
          } else if (p.op == '>') {
            return SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
          } else {
            return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
          }
        }
      }

      final strict = p.op == '<' || p.op == '>';
      final lb = strict ? '(' : '[';
      final rb = strict ? ')' : ']';
      final between = (p.op == '<' || p.op == '""" + U_LEQ + """') ? p.a > 0 : p.a < 0;

      if (between) {
        final innerOp = strict ? '<' : '""" + U_LEQ + """';
        return SolveResult(
          answer: '${_fmt(lo)} $innerOp x $innerOp ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '$lb${_fmt(lo)}, ${_fmt(hi)}$rb',
        );
      } else {
        return SolveResult(
          answer: 'x ${strict ? '<' : '""" + U_LEQ + """'} ${_fmt(lo)} or x ${strict ? '>' : '""" + U_GEQ + """'} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '(-""" + U_INFINITY + """, ${_fmt(lo)}$rb """ + U_UNION + """ $lb${_fmt(hi)}, """ + U_INFINITY + """)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    // Step 1: Original inequality
    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final disc = p.b * p.b - 4 * p.a * p.c;

    // Step 2: Standard form (if input wasn't already ax\\u00b2+bx+c op 0)
    final aCoef = _coefLatex(p.a);
    final bCoef = p.b == 0 ? '' : (p.b > 0 ? '+ ${_fmtLatex(p.b)}x' : '- ${_fmtLatex(-p.b)}x');
    final cCoef = p.c == 0 ? '' : (p.c > 0 ? '+ ${_fmtLatex(p.c)}' : '- ${_fmtLatex(-p.c)}');
    final stdForm = '${aCoef}x^2 $bCoef $cCoef ${p.op} 0'.replaceAll('  ', ' ').trim();
    final inputNorm = input.trim().replaceAll(' ', '');
    if (stdForm.replaceAll(' ', '') != inputNorm) {
      final dets = [input.trim()];
      final opStr = _extractOp(inputNorm);
      if (opStr != null) {
        final opIdx = _findOpIndex(inputNorm, opStr);
        if (opIdx != -1) {
          final lhs = inputNorm.substring(0, opIdx).trim();
          final rhs = inputNorm.substring(opIdx + opStr.length).trim();
          if (rhs != '0') {
            final pRhs = rhs.contains('x') ? '($rhs)' : rhs;
            dets.add('$lhs - $pRhs ${p.op} $rhs - $pRhs');
            dets.add('$lhs - $pRhs ${p.op} 0');
          }
        }
      }
      if (dets.last != stdForm) dets.add(stdForm);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Move all terms to one side',
        details: dets,
        latex: stdForm,
      ));
    }

    // Step 3: Discriminant
    final bSq = p.b * p.b;
    final ac4 = 4 * p.a * p.c;
    steps.add(StepModel(
      stepNumber: n++,
      hint: disc < 0
          ? 'Negative discriminant \\\\Delta = ${_fmt(disc)} — no real roots'
          : disc == 0
              ? 'Zero discriminant \\\\Delta = 0 — one repeated root'
              : 'Positive discriminant \\\\Delta = ${_fmt(disc)} — two real roots',
      details: [
        r'\\Delta = b^2 - 4ac',
        r'\\Delta = (' + _fmtLatex(p.b) + ')^2 - 4(' + _fmtLatex(p.a) + ')(' + _fmtLatex(p.c) + ')',
        r'\\Delta = ' + _fmtLatex(bSq) + ' - ' + _fmtLatex(ac4),
        r'\\Delta = ' + _fmtLatex(disc),
      ],
      latex: r'\\Delta = ' + _fmtLatex(disc),
    ));

    if (disc < 0) {
      final allSat = p.a > 0
          ? (p.op == '>' || p.op == '""" + U_GEQ + """')
          : (p.op == '<' || p.op == '""" + U_LEQ + """');
      steps.add(StepModel(
        stepNumber: n++,
        hint: allSat
            ? 'Always true — parabola never crosses x-axis'
            : 'Always false — parabola never crosses x-axis',
        details: [
          r'\\Delta < 0 \\implies \\text{no real roots}',
          p.a > 0
              ? r'a > 0 \\implies \\text{parabola opens up, entirely above x-axis}'
              : r'a < 0 \\implies \\text{parabola opens down, entirely below x-axis}',
          allSat
              ? r'\\text{Inequality holds for all } x'
              : r'\\text{Inequality never holds}',
        ],
        latex: allSat ? r'(-\\infty, \\infty)' : r'\\emptyset',
      ));
      return steps;
    }

    if (disc == 0) {
      final root = -p.b / (2 * p.a);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Repeated root at x = ${_fmt(root)}',
        details: [
          r'x = \\frac{-b}{2a}',
          r'x = \\frac{' + _fmtLatex(-p.b) + '}{2(' + _fmtLatex(p.a) + ')}',
          r'x = ' + _fmtLatex(root),
        ],
        latex: r'x = ' + _fmtLatex(root),
      ));
      final result = solve(input);
      steps.add(StepModel(
        stepNumber: n++,
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
      return steps;
    }

    // --- disc > 0: Two distinct real roots ---

    final sqrtD = math.sqrt(disc);
    final r1Val = (-p.b - sqrtD) / (2 * p.a);
    final r2Val = (-p.b + sqrtD) / (2 * p.a);
    final loLatex = r1Val < r2Val
        ? _fmtSurd(p.a, p.b, disc.round(), false)
        : _fmtSurd(p.a, p.b, disc.round(), true);
    final hiLatex = r1Val < r2Val
        ? _fmtSurd(p.a, p.b, disc.round(), true)
        : _fmtSurd(p.a, p.b, disc.round(), false);

    // Step 4: Quadratic formula -- find roots
    final negB = _fmtLatex(-p.b);
    final twoA = _fmtLatex(2 * p.a);
    final sqrtDisc = _sqrtSimplify(disc.round());
    final root1 = _fmtSurd(p.a, p.b, disc.round(), false);
    final root2 = _fmtSurd(p.a, p.b, disc.round(), true);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Find the roots',
      details: [
        r'x = \\frac{-b \\pm \\sqrt{\\Delta}}{2a}',
        r'x = \\frac{' + negB + r' \\pm \\sqrt{' + _fmtLatex(disc) + '}}{' + twoA + '}',
        r'x_1 = \\frac{' + negB + r' - ' + sqrtDisc + '}{' + twoA + '} = ' + root1,
        r'x_2 = \\frac{' + negB + r' + ' + sqrtDisc + '}{' + twoA + '} = ' + root2,
      ],
      latex: r'x_1 = ' + root1 + r',\\quad x_2 = ' + root2,
    ));

    // Step 5: Sign and solution
    final opensUp = p.a > 0;
    final between = (p.op == '<' || p.op == '""" + U_LEQ + """') ? opensUp : !opensUp;

    String solLatex;
    if (between) {
      solLatex = loLatex + r' < x < ' + hiLatex;
    } else {
      solLatex = r'x < ' + loLatex + r' \\quad\\text{or}\\quad x > ' + hiLatex;
    }

    steps.add(StepModel(
      stepNumber: n++,
      hint: opensUp ? 'Parabola opens upward' : 'Parabola opens downward',
      details: [
        opensUp
            ? r'\\text{Positive outside, negative between}'
            : r'\\text{Negative outside, positive between}',
        solLatex,
      ],
      latex: solLatex,
    ));

    final result = solve(input);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Solution in interval notation',
      latex: _toLatexInterval(result.intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = _findOpIndex(s, op);
    if (idx == -1) return null;

    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final lp = _parseQuad(lhs);
    final rp = _parseQuad(rhs);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['a']! - rp['a']!,
      b: lp['b']! - rp['b']!,
      c: lp['c']! - rp['c']!,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static int _findOpIndex(String s, String op) {
    if (op == '>' || op == '<') {
      for (int i = s.length - 1; i >= 0; i--) {
        if (s[i] == op) {
          if (i + 1 < s.length && s[i + 1] == '=') continue;
          return i;
        }
      }
      return -1;
    }
    return s.indexOf(op);
  }

  static Map<String, double>? _parseQuad(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    double a = 0, b = 0, c = 0;
    final tokens = <String>[];
    int depth = 0;
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if (ch == '(') { depth++; cur += ch; }
      else if (ch == ')') { depth--; cur += ch; }
      else if ((ch == '+' || ch == '-') && i > 0 && depth == 0 && cur.isNotEmpty) {
        tokens.add(cur); cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      final t = tok.replaceAll('*', '');
      if (t.contains('x^2')) {
        final cs = t.substring(0, t.indexOf('x'));
        a += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else if (t.contains('x')) {
        final cs = t.substring(0, t.indexOf('x'));
        b += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else {
        final clean = t.startsWith('+') ? t.substring(1) : t;
        c += double.tryParse(clean) ?? 0;
      }
    }
    return {'a': a, 'b': b, 'c': c};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

  static SolveResult _solveLinear(double b, double c, String op) {
    if (b == 0) {
      final sat = _evalOp(c, op, 0);
      return SolveResult(
        answer: sat ? 'All real numbers' : 'No solution',
        points: [],
        intervalNotation: sat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
      );
    }
    final x = -c / b;
    final finalOp = b < 0 ? _flipOp(op) : op;
    return SolveResult(
      answer: 'x $finalOp ${_fmt(x)}',
      points: [x],
      intervalNotation: _interval(finalOp, x),
    );
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_FLIPOP + FMT_EVALOP + """

  /// Simplify sqrt(n) into a\\sqrt{b} form, e.g. sqrt(32) -> 4\\sqrt{2}
  static String _sqrtSimplify(int n) {
    if (n <= 0) return '0';
    int sq = 1, rem = n;
    for (int i = 2; i * i <= rem; i++) {
      while (rem % (i * i) == 0) {
        sq *= i;
        rem ~/= (i * i);
      }
    }
    if (rem == 1) return sq.toString();
    if (sq == 1) return r'\\sqrt{' + rem.toString() + '}';
    return sq.toString() + r'\\sqrt{' + rem.toString() + '}';
  }

  /// Format a root (-b +/- sqrt(Delta))/(2a) in simplified radical form.
  /// Falls back to _fmtLatex for rational roots.
  static String _fmtSurd(double a, double b, int disc, bool plus) {
    final sqrtVal = math.sqrt(disc);
    if (sqrtVal == sqrtVal.roundToDouble()) {
      return _fmtLatex((-b + (plus ? 1 : -1) * sqrtVal) / (2 * a));
    }
    final sqrtStr = _sqrtSimplify(disc);
    final sign = plus ? '+' : '-';
    if (b == 0) {
      final den = (2 * a).round();
      final m = RegExp(r'^(\d+)\\\\sqrt\{').firstMatch(sqrtStr);
      if (m != null) {
        final coeff = int.parse(m[1]!);
        if (den != 0 && coeff % den.abs() == 0) {
          final c = coeff ~/ den.abs();
          final rem = sqrtStr.substring(m[1]!.length);
          if (a < 0) return (plus ? '-' : '') + (c == 1 ? '' : c.toString()) + rem;
          return (plus ? '' : '-') + (c == 1 ? '' : c.toString()) + rem;
        }
      }
      if (den == 1 || den == -1) return (plus ? '' : '-') + sqrtStr;
      return r'\\frac{' + (a < 0 == plus ? '' : '-') + sqrtStr + '}{' + _fmtLatex(2 * a) + '}';
    }
    return r'\\frac{' + _fmtLatex(-b) + ' ' + sign + ' ' + sqrtStr + '}{' + _fmtLatex(2 * a) + '}';
  }

  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, """ + U_INFINITY + """)';
      case '""" + U_GEQ + """': return '[$bs, """ + U_INFINITY + """)';
      case '<': return '(-""" + U_INFINITY + """, $bs)';
      case '""" + U_LEQ + """': return '(-""" + U_INFINITY + """, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, c;
  const _Parsed({required this.op, required this.a, required this.b, required this.c});
}
"""


# ─── ABSOLUTE VALUE SOLVER ─────────────────────────────────────────

ABS_CODE = DART_HEADER + """
class GeneratedAbsoluteSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse absolute value inequality.');

      bool absOnLeft = p.absOnLeft;
      String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
      final isNarrow = effectiveOp == '<' || effectiveOp == '""" + U_LEQ + """';

      if (isNarrow) {
        if (p.k < 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '<') return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '""" + U_LEQ + """') {
          if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
          final root = -p.b / p.a;
          return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
        }
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final lb = effectiveOp == '<' ? '(' : '[';
        final rb = effectiveOp == '<' ? ')' : ']';
        return SolveResult(
          answer: '${_fmt(l)} $effectiveOp x $effectiveOp ${_fmt(h)}',
          points: [l, h],
          intervalNotation: '$lb${_fmt(l)}, ${_fmt(h)}$rb',
        );
      } else {
        if (p.k < 0) return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
        if (p.k == 0 && effectiveOp == '""" + U_GEQ + """') return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '>') {
          final root = -p.b / p.a;
          final fR = _fmt(root);
          return SolveResult(answer: 'x < $fR or x > $fR', points: [root], intervalNotation: '(-""" + U_INFINITY + """, $fR) """ + U_UNION + """ ($fR, """ + U_INFINITY + """)');
        }

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final b1 = effectiveOp == '>' ? ')' : ']';
        final b2 = effectiveOp == '>' ? '(' : '[';
        final fL = _fmt(l);
        final fH = _fmt(h);
        final flipOp = _flipOp(effectiveOp);
        return SolveResult(
          answer: 'x $flipOp $fL or x $effectiveOp $fH',
          points: [l, h],
          intervalNotation: '(-""" + U_INFINITY + """, $fL$b1 """ + U_UNION + """ $b2$fH, """ + U_INFINITY + """)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    // Step 1: Show the original inequality with proper absolute value delimiters
    steps.add(StepModel(
      stepNumber: n++,
      latex: _absToLatex(input.trim()),
    ));

    final innerStr = p.b == 0 ? '${_coefLatex(p.a)}x' : '${_coefLatex(p.a)}x ${p.b >= 0 ? "+ ${_fmtLatex(p.b)}" : "- ${_fmtLatex(p.b.abs())}"}';
    final kStr = _fmtLatex(p.k);
    final absOnLeft = p.absOnLeft;
    final effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
    final isNarrow = effectiveOp == '<' || effectiveOp == '""" + U_LEQ + """';

    // ---- Edge cases ----
    if (p.a == 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'No variable term — evaluate the constant directly',
        latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
      ));
      return steps;
    }

    if (p.k < 0) {
      if (isNarrow) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Absolute value is always \\u2265 0, so it can never be < ${_fmt(p.k)}',
          latex: r'\emptyset',
        ));
      } else {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Absolute value is always \\u2265 0, which is always \\u2265 ${_fmt(p.k)}',
          latex: r'(-\infty, \infty)',
        ));
      }
      return steps;
    }

    if (p.k == 0 && effectiveOp == '<') {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Absolute value is always \\u2265 0, so |expr| < 0 has no solution',
        latex: r'\emptyset',
      ));
      return steps;
    }

    if (p.k == 0 && effectiveOp == '>') {
      // |ax+b| > 0  =>  ax+b \u2260 0  =>  x \u2260 -b/a
      final root = _fmtLatex(-p.b / p.a);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Absolute value is always \\u2265 0, so |expr| > 0 means expr \\u2260 0',
        latex: r'x \\neq ' + root,
      ));
      steps.add(StepModel(
        stepNumber: n++,
        latex: r'(-\infty, ' + root + r') \cup (' + root + r', \infty)',
      ));
      return steps;
    }

    // ---- Common computations ----
    final flipOp = _flipOp(effectiveOp);
    final negKStr = _fmtLatex(-p.k);
    final v1 = (-p.k - p.b) / p.a;
    final v2 = (p.k - p.b) / p.a;
    final l = v1 < v2 ? v1 : v2;
    final h = v1 < v2 ? v2 : v1;
    final result = solve(input);

    // Pre-compute formatted strings for reuse
    final leftConst = _fmtLatex(-p.k - p.b);
    final rightConst = _fmtLatex(p.k - p.b);

    if (isNarrow) {
      // ──────────────────────────────────────────────────────────
      // NARROW CASE  |ax+b| < k  \u2192  -k < ax+b < k
      // Steps: Rule \u2192 Isolate x-term \u2192 Divide \u2192 Interval
      // ──────────────────────────────────────────────────────────

      // ──────────────────────────────────────────────────────────
      // Step 2: Apply Theorem 1 — |X| < k  =>  -k < X < k
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Apply Theorem 1',
        details: [
          _absToLatex(input.trim()),
          r'\\Downarrow',
          r'\\text{Theorem 1: } |X| ' + _texOp(effectiveOp) + r' k \\Rightarrow -k ' + _texOp(effectiveOp) + r' X ' + _texOp(effectiveOp) + r' k',
          '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
      ));

      // ──────────────────────────────────────────────────────────
      // Step 3: Isolate x-term — subtract/add constant
      if (p.b != 0) {
        final bAbs = _fmtLatex(p.b.abs());
        final bStr = _fmtLatex(p.b);
        final amount = p.b > 0 ? _fmt(p.b) : _fmt(-p.b);
        final opWord = p.b > 0 ? 'Subtract' : 'Add';
        final leftArith = p.b > 0
            ? '$negKStr - $bAbs'
            : '$negKStr + $bAbs';
        final midArith = p.b > 0
            ? '${_coefLatex(p.a)}x + $bStr - $bAbs'
            : '${_coefLatex(p.a)}x - $bAbs + $bAbs';
        final rightArith = p.b > 0
            ? '$kStr - $bAbs'
            : '$kStr + $bAbs';
        steps.add(StepModel(
          stepNumber: n++,
          hint: '$opWord $amount from all three parts',
          details: [
            '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
            r'\\Downarrow',
            '$leftArith ${_texOp(effectiveOp)} $midArith ${_texOp(effectiveOp)} $rightArith',
            r'\\Downarrow',
            '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
          ],
          latex: '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
        ));
      }

      // ──────────────────────────────────────────────────────────
      // Step 4: Divide by x-coefficient
      if (p.a != 1 && p.a != -1) {
        final finalOpNarrow = p.a < 0 ? _flipOp(effectiveOp) : effectiveOp;
        final aStr = _fmtLatex(p.a);
        steps.add(StepModel(
          stepNumber: n++,
          hint: p.a < 0
              ? 'Divide all parts by ${_fmt(p.a.abs())}, flip inequality signs'
              : 'Divide all parts by ${_fmt(p.a)}',
          details: [
            '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
            r'\\Downarrow',
            r'\\frac{' + _fmtLatex(-p.k - p.b) + '}{' + aStr + '} ' + _texOp(finalOpNarrow) + r' \\frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(finalOpNarrow) + r' \\frac{' + _fmtLatex(p.k - p.b) + '}{' + aStr + '}',
            r'\\Downarrow',
            '${_fmtLatex(l)} ${_texOp(finalOpNarrow)} x ${_texOp(finalOpNarrow)} ${_fmtLatex(h)}',
          ],
          latex: '${_fmtLatex(l)} ${_texOp(finalOpNarrow)} x ${_texOp(finalOpNarrow)} ${_fmtLatex(h)}',
        ));
      } else if (p.a == -1) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Multiply all parts by -1, flip signs',
          details: [
            '$leftConst ${_texOp(effectiveOp)} -x ${_texOp(effectiveOp)} $rightConst',
            r'\\Downarrow',
            '${_fmtLatex(l)} ${_texOp(effectiveOp)} x ${_texOp(effectiveOp)} ${_fmtLatex(h)}',
          ],
          latex: '${_fmtLatex(l)} ${_texOp(effectiveOp)} x ${_texOp(effectiveOp)} ${_fmtLatex(h)}',
        ));
      }

      // ──────────────────────────────────────────────────────────
      // Final: Interval notation
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Write solution in interval notation',
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
    } else {
      // ──────────────────────────────────────────────────────────
      // WIDE CASE  |ax+b| > k  \u2192  ax+b < -k  OR  ax+b > k
      // Steps: Rule \u2192 Solve Left \u2192 Solve Right \u2192 Combine \u2192 Interval
      // ──────────────────────────────────────────────────────────

      // ──────────────────────────────────────────────────────────
      // Step 2: Apply Theorem 2 — |X| > k  =>  X < -k  or  X > k
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Apply Theorem 2',
        details: [
          _absToLatex(input.trim()),
          r'\\Downarrow',
          r'\\text{Theorem 2: } |X| ' + _texOp(effectiveOp) + r' k \\Rightarrow X ' + _texOp(flipOp) + r' -k \\text{ or } X ' + _texOp(effectiveOp) + r' k',
          '$innerStr ${_texOp(flipOp)} $negKStr \\\\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$innerStr ${_texOp(flipOp)} $negKStr \\\\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
      ));

      final leftOp = p.a < 0 ? _flipOp(flipOp) : flipOp;
      final leftVal = _fmtLatex((-p.k - p.b) / p.a);
      final rightOp = p.a < 0 ? _flipOp(effectiveOp) : effectiveOp;
      final rightVal = _fmtLatex((p.k - p.b) / p.a);

      // ──────────────────────────────────────────────────────────
      // Step 3: Isolate x-term in both branches
      if (p.b != 0) {
        final lConst = _fmtLatex(-p.k - p.b);
        final rConst = _fmtLatex(p.k - p.b);
        final bAbs = _fmtLatex(p.b.abs());
        final bStr = _fmtLatex(p.b);
        final amount = p.b > 0 ? _fmt(p.b) : _fmt(-p.b);
        final opWord = p.b > 0 ? 'Subtract' : 'Add';
        final leftArith = p.b > 0
            ? '$negKStr - $bAbs'
            : '$negKStr + $bAbs';
        final rightArith = p.b > 0
            ? '$kStr - $bAbs'
            : '$kStr + $bAbs';
        final midArith = p.b > 0
            ? '${_coefLatex(p.a)}x + $bStr - $bAbs'
            : '${_coefLatex(p.a)}x - $bAbs + $bAbs';
        steps.add(StepModel(
          stepNumber: n++,
          hint: '$opWord $amount from both sides of each inequality',
          details: [
            '$innerStr ${_texOp(flipOp)} $negKStr \\\\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
            r'\\Downarrow',
            '$midArith ${_texOp(flipOp)} $leftArith \\\\text{ or } $midArith ${_texOp(effectiveOp)} $rightArith',
            r'\\Downarrow',
            '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lConst \\\\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rConst',
          ],
          latex: '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lConst \\\\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rConst',
        ));
      }

      // Step 4: Divide by coefficient in both branches
      if (p.a != 1 && p.a != -1) {
        final aStr = _fmtLatex(p.a);
        final lcStr = _fmtLatex(-p.k - p.b);
        final rcStr = _fmtLatex(p.k - p.b);
        steps.add(StepModel(
          stepNumber: n++,
          hint: p.a < 0 ? 'Divide both sides by ${_fmt(p.a.abs())}, flip signs' : 'Divide both sides by ${_fmt(p.a)}',
          details: [
            '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lcStr \\\\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rcStr',
            r'\\Downarrow',
            r'\\frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(leftOp) + r' \\frac{' + lcStr + '}{' + aStr + '} \\\\text{ or } ' + r'\\frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(rightOp) + r' \\frac{' + rcStr + '}{' + aStr + '}',
            r'\\Downarrow',
            'x ${_texOp(leftOp)} ${leftVal} \\\\text{ or } x ${_texOp(rightOp)} ${rightVal}',
          ],
          latex: 'x ${_texOp(leftOp)} ${leftVal} \\\\text{ or } x ${_texOp(rightOp)} ${rightVal}',
        ));
      } else if (p.a == -1) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Multiply by -1, flip signs',
          details: [
            'x ${_texOp(leftOp)} ${leftVal} \\\\text{ or } x ${_texOp(rightOp)} ${rightVal}',
          ],
          latex: 'x ${_texOp(leftOp)} ${leftVal} \\\\text{ or } x ${_texOp(rightOp)} ${rightVal}',
        ));
      }

      // ──────────────────────────────────────────────────────────
      // Step 5: Interval notation
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Combine into solution set',
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
    }


    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('\u2212', '-')
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    if (!s.contains('|')) return null;

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);

    bool absOnLeft;
    String absSide, constStr;
    if (left.contains('|')) {
      absSide = left; constStr = right; absOnLeft = true;
    } else if (right.contains('|')) {
      absSide = right; constStr = left; absOnLeft = false;
    } else {
      return null;
    }

    final inner = absSide.replaceAll('|', '');
    final k = double.tryParse(constStr);
    if (k == null) return null;

    final parsed = _parseLinear(inner);
    if (parsed == null) return null;

    return _Parsed(op: op, a: parsed['x']!, b: parsed['c']!, k: k, absOnLeft: absOnLeft);
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + FMT_FLIPOP + """

  /// Replace |...| with \\lvert...\\rvert for proper LaTeX absolute value rendering
  static String _absToLatex(String s) {
    final buf = StringBuffer();
    bool inAbs = false;
    for (int i = 0; i < s.length; i++) {
      if (s[i] == '|') {
        if (!inAbs) {
          buf.write(r'\lvert ');
          inAbs = true;
        } else {
          buf.write(r' \\rvert');
          inAbs = false;
        }
      } else {
        buf.write(s[i]);
      }
    }
    return buf.toString();
  }
}

class _Parsed {
  final String op;
  final double a, b, k;
  final bool absOnLeft;
  const _Parsed({required this.op, required this.a, required this.b, required this.k, required this.absOnLeft});
}
"""


# ─── RATIONAL SOLVER ───────────────────────────────────────────────

RAT_CODE = DART_HEADER + """
class GeneratedRationalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse rational expression.');

      final intervals = _buildIntervals(p);
      if (intervals.isEmpty) {
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
      }

      return SolveResult(
        answer: intervals.join(' or '),
        points: _criticalPoints(p),
        intervalNotation: intervals.join(' """ + U_UNION + """ '),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final combStr = _linearStrLatex(p.combA, p.combC);
    final denStr = _linearStrLatex(p.denA, p.denC);

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Combine into a single fraction, set to zero',
      latex: r'\\frac{' + combStr + r'}{' + denStr + r'} ' + _texOp(p.op) + ' 0',
    ));

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Find critical points from numerator and denominator',
      latex: (p.combA != 0 ? '$combStr = 0' : '') + r' \\text{ and } ' + (p.denA != 0 ? '$denStr = 0' : ''),
    ));

    final intervals = _buildIntervals(p);
    final intervalStr = intervals.isEmpty ? '""" + U_EMPTY + """' : intervals.join(' """ + U_UNION + """ ');

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(intervalStr),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;
    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final slashIdx = lhs.indexOf('/');
    if (slashIdx == -1) return null;

    final numStr = lhs.substring(0, slashIdx).replaceAll('(', '').replaceAll(')', '');
    final denStr = lhs.substring(slashIdx + 1).replaceAll('(', '').replaceAll(')', '');
    final rhsVal = double.tryParse(rhs.trim()) ?? 0.0;

    final numP = _parseLinear(numStr);
    final denP = _parseLinear(denStr);
    if (numP == null || denP == null) return null;

    final numA = numP['x']!;
    final numC = numP['c']!;
    final denA = denP['x']!;
    final denC = denP['c']!;

    return _Parsed(
      op: op, numA: numA, numC: numC,
      denA: denA, denC: denC, rhs: rhsVal,
      combA: numA - rhsVal * denA,
      combC: numC - rhsVal * denC,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static List<double> _criticalPoints(_Parsed p) {
    final pts = <double>[];
    if (p.combA != 0) pts.add(-p.combC / p.combA);
    if (p.denA != 0) pts.add(-p.denC / p.denA);
    return pts.toSet().toList();
  }

  static bool _satisfies(double x, _Parsed p) {
    final den = p.denA * x + p.denC;
    if (den == 0) return false;
    final val = (p.combA * x + p.combC) / den;
    return _evalOp(val, p.op, 0);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + FMT_EVALOP + """

  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }

  static List<String> _buildIntervals(_Parsed p) {
    final strict = p.op == '<' || p.op == '>';
    final denZero = p.denA != 0 ? -p.denC / p.denA : double.nan;
    final undefinedPts = <double>{if (!denZero.isNaN) denZero};

    final pts = _criticalPoints(p)..sort();
    if (pts.isEmpty) return [];

    final testPts = <double>[
      pts.first - 1,
      for (int i = 0; i < pts.length - 1; i++) (pts[i] + pts[i + 1]) / 2,
      pts.last + 1,
    ];

    final solution = <String>[];
    for (int i = 0; i < testPts.length; i++) {
      if (!_satisfies(testPts[i], p)) continue;
      if (i == 0) {
        final hi = pts[0];
        solution.add('(-""" + U_INFINITY + """, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      } else if (i == testPts.length - 1) {
        final lo = pts.last;
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, """ + U_INFINITY + """)');
      } else {
        final lo = pts[i - 1];
        final hi = pts[i];
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      }
    }
    return solution;
  }
}

class _Parsed {
  final String op;
  final double numA, numC, denA, denC, rhs, combA, combC;
  const _Parsed({
    required this.op,
    required this.numA, required this.numC,
    required this.denA, required this.denC,
    required this.rhs,
    required this.combA, required this.combC,
  });
}
"""


# ─── RADICAL SOLVER ────────────────────────────────────────────────

RAD_CODE = DART_HEADER + """
class GeneratedRadicalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse radical inequality.');

      // For sqrt(bx + c) op k
      if (p.k < 0) {
        if (p.op == '>' || p.op == '""" + U_GEQ + """') {
          return SolveResult(answer: 'x """ + U_GEQ + """ ${_fmt(-p.c / p.b)} (domain only)', points: [], intervalNotation: '');
        }
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
      }

      // Domain: bx + c >= 0  =>  x >= -c/b (if b > 0) or x <= -c/b (if b < 0)
      final domainBoundary = -p.c / p.b;
      final domainReversed = p.b < 0;

      // Square: bx + c op k^2  =>  x op (k^2 - c) / b
      final kSq = p.k * p.k;
      final squaredBoundary = (kSq - p.c) / p.b;

      // Combine domain and squared inequality
      // Case analysis based on operation
      String answer, interval;
      final f = _fmt;
      final dB = f(domainBoundary);
      final sB = f(squaredBoundary);

      if (p.op == '<' || p.op == '""" + U_LEQ + """') {
        // sqrt(...) < k => domain AND x < (k^2 - c)/b
        // Upper bound is min of what?
        if (domainReversed) {
          answer = '$sB """ + U_LEQ + """ x """ + U_LEQ + """ $dB';
          interval = '[$sB, $dB]';
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'No solution';
            interval = '""" + U_EMPTY + """';
          } else {
            answer = '$dB """ + U_LEQ + """ x $sB';
            interval = '[$dB, $sB]';
          }
        }
      } else {
        // sqrt(...) > k => domain AND x > (k^2 - c)/b
        if (domainReversed) {
          if (squaredBoundary < domainBoundary) {
            answer = 'x """ + U_GEQ + """ $dB';
            interval = '[$dB, """ + U_INFINITY + """)';
          } else {
            answer = 'x """ + U_GEQ + """ $sB';
            interval = '[$sB, """ + U_INFINITY + """)';
          }
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'x """ + U_GEQ + """ $dB';
            interval = '[$dB, """ + U_INFINITY + """)';
          } else {
            answer = 'x """ + U_GEQ + """ $sB';
            interval = '[$sB, """ + U_INFINITY + """)';
          }
        }
      }

      final pts = <double>[domainBoundary];
      if (squaredBoundary.isFinite && squaredBoundary != domainBoundary) {
        pts.add(squaredBoundary);
      }
      pts.sort();

      return SolveResult(answer: answer, points: pts, intervalNotation: interval);
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final radStrLatex = _linearStrLatex(p.b, p.c);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Radicand must be non-negative for real solutions',
      latex: r'\\text{' + radStrLatex + r'} \\geq 0',
    ));

    if (p.k >= 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Square both sides to eliminate the radical',
        details: [
          r'(' + radStrLatex + r')^2 ' + '${_texOp(p.op)} ' + '${_fmtLatex(p.k)}^2',
          '$radStrLatex ${_texOp(p.op)} ${_fmtLatex(p.k * p.k)}',
        ],
        latex: '$radStrLatex ${_texOp(p.op)} ${_fmtLatex(p.k * p.k)}',
      ));
    }

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .toLowerCase()
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """')
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll('\\u221a', 'sqrt');

    final op = _extractOp(s);
    if (op == null) return null;

    // Find operator at top level (not inside parentheses)
    int depth = 0;
    int opIdx = -1;
    for (int i = 0; i < s.length; i++) {
      if (s[i] == '(') depth++;
      if (s[i] == ')') depth--;
      if (depth != 0) continue;
      if (s[i] == op) {
        // Check for multi-char ops
        if (op == '""" + U_GEQ + """' && i > 0) {
          if (s[i - 1] == '>') continue; // already matched with >
        }
        opIdx = i;
        break;
      }
    }
    if (opIdx == -1) return null;

    final lhs = s.substring(0, opIdx);
    final rhs = s.substring(opIdx + op.length);

    bool sqrtOnLeft = lhs.contains('sqrt');
    bool sqrtOnRight = rhs.contains('sqrt');
    if (!sqrtOnLeft && !sqrtOnRight) return null;

    String sqrtSide = sqrtOnLeft ? lhs : rhs;
    String constSide = sqrtOnLeft ? rhs : lhs;

    final sqrtMatch = RegExp(r'sqrt\(([^)]+)\)').firstMatch(sqrtSide);
    if (sqrtMatch == null) return null;
    final radicand = sqrtMatch.group(1)!;

    final k = double.tryParse(constSide.trim());
    if (k == null) return null;

    final parsed = _parseLinear(radicand);
    if (parsed == null) return null;

    return _Parsed(op: op, b: parsed['x']!, c: parsed['c']!, k: k);
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + """
}

class _Parsed {
  final String op;
  final double b, c, k;
  const _Parsed({required this.op, required this.b, required this.c, required this.k});
}
"""


# ─── MAIN ──────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("MathCalcu - Dart Solver Generator")
    print("Generating SymPy-verified Dart solver files...")
    print("=" * 60)
    print()

    # Verify with SymPy first
    sympy_run_tests("Linear", [
        ("2*x + 1 > 5", "x > 2"),
        ("3*x - 7 <= 8", "x <= 5"),
        ("-4*x + 3 < 11", "x > -2"),
    ])
    sympy_run_tests("Quadratic", [
        ("x**2 - 4 > 0", "x < -2 or x > 2"),
        ("x**2 - 5*x + 6 <= 0", "2 <= x <= 3"),
    ])
    sympy_run_tests("Absolute", [
        ("Abs(x) < 3", "-3 < x < 3"),
        ("Abs(2*x - 1) >= 3", "x <= -1 or x >= 2"),
        ("Abs(x) > 0", "x < 0 or x > 0"),
        ("Abs(x) >= 0", "All real numbers"),
        ("Abs(x) < 0", "No solution"),
        ("Abs(x) <= 0", "x = 0"),
        ("Abs(2*x - 3) <= 5", "-1 <= x <= 4"),
        ("Abs(4 - 3*x) > 7", "x < -1 or x > 11/3"),
    ])
    sympy_run_tests("Rational", [
        ("(x+1)/(x-2) > 0", "x < -1 or x > 2"),
    ])

    print("\n" + "-" * 60)
    print("Generating Dart files...\n")

    write_dart("generated_linear_solver.dart", LINEAR_CODE)
    write_dart("generated_quadratic_solver.dart", QUAD_CODE)
    write_dart("generated_absolute_solver.dart", ABS_CODE)
    write_dart("generated_rational_solver.dart", RAT_CODE)
    write_dart("generated_radical_solver.dart", RAD_CODE)

    print("\n" + "=" * 60)
    print("Done! 5 Dart solver files generated in lib/midterm/solvers/inequalities_solver/")
    print("=" * 60)


if __name__ == "__main__":
    main()
