#!/usr/bin/env python3
"""
MathCalcu - Python Code Generator for Dart Math Solvers
Uses SymPy to verify correctness and generate Dart solver files.
All computation happens in generated Dart code at runtime (100% offline).
"""
import json, re, sys
from pathlib import Path
from sympy import (
    symbols, solve_univariate_inequality, oo, latex, sympify, sqrt,
    parse_expr, Interval, S, Poly, degree, LC, solve, factor, simplify
)

x = symbols("x")
PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = PROJECT_ROOT / "python_solvers" / "generated"
DART_LIB_DIR = PROJECT_ROOT / "lib" / "midterm" / "solvers" / "inequalities_solver"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
DART_LIB_DIR.mkdir(parents=True, exist_ok=True)

# Unicode chars used in Dart output
U_INFINITY = '\u221e'
U_INFINITY_LATEX = r'\infty'  # LaTeX infinity for raw Dart strings
U_INFINITY_LATEX_NR = '\\\\infty'  # LaTeX infinity for non-raw Dart strings (Dart: \\ → \)
U_EMPTY = '\u2205'
U_EMPTY_LATEX = r'\emptyset'  # LaTeX empty set for raw Dart strings
U_EMPTY_LATEX_NR = '\\\\emptyset'  # LaTeX empty set for non-raw Dart strings
U_UNION = '\u222a'
U_UNION_LATEX = r'\cup'  # LaTeX union for raw Dart strings
U_UNION_LATEX_NR = '\\\\cup'  # LaTeX union for non-raw Dart strings
U_SQUARED = '\u00b2'
U_GEQ = '\u2265'
U_LEQ = '\u2264'
U_DELTA = '\u0394'
U_CHECK = '\u2713'
U_TIMES = '\u00d7'

def to_latex(e):
    try: return latex(e)
    except: return str(e)

def write_json(fn, data):
    p = OUTPUT_DIR / fn
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"  + JSON: {p.name}")

def write_dart(fn, content):
    p = DART_LIB_DIR / fn
    content = re.sub(
        r"\s+title:\s*'[^']*',\s*\n\s+explanation:\s*'[^']*',\s*\n",
        "\n",
        content,
    )
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  + Dart: {p.name}")


# ─── SymPy Verification ────────────────────────────────────────────

def sympy_solve_inequality(expr_str):
    try:
        expr = parse_expr(expr_str)
        sol = solve_univariate_inequality(expr, x, relational=False)
        return sol
    except Exception as e:
        return None

def sympy_run_tests(solver_name, test_cases):
    """Run test cases through SymPy and report results."""
    print(f"\n  Verifying {solver_name} with SymPy...")
    for expr_str, expected_desc in test_cases:
        sol = sympy_solve_inequality(expr_str)
        status = "OK" if sol is not None else "FAIL"
        print(f"    {expr_str} -> {status} (expected: {expected_desc})")


# ─── Dart Code Templates ───────────────────────────────────────────

DART_HEADER = """// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';

"""

# Helper: format a double nicely with fraction support
FMT_COMMON = """
  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-{INF}' : '{INF}');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);
""".replace('{INF}', U_INFINITY)

FMT_TEXOP = """
  static String _texOp(String op) {
    switch (op) {
      case '{GEQ}': return '\\\\geq';
      case '{LEQ}': return '\\\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

FMT_FLIPOP = """
  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '{GEQ}': return '{LEQ}';
      case '{LEQ}': return '{GEQ}';
      default: return op;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

FMT_EVALOP = """
  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '{GEQ}': return left >= right;
      case '{LEQ}': return left <= right;
      default: return false;
    }
  }
""".replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

# LaTeX-compatible number formatter
FMT_COMMON_LATEX = """
  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-{INF}' : r'{INF}');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }
""".replace('{INF}', U_INFINITY_LATEX)

# LaTeX interval converter (converts plain-text intervals to LaTeX)
FMT_TOLATEX = """
  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\\u221e', r'{INF}')
        .replaceAll('\\u2205', r'{EMPTY}')
        .replaceAll('\\u222a', r'{UNION}');
  }
""".replace('{INF}', U_INFINITY_LATEX).replace('{EMPTY}', U_EMPTY_LATEX).replace('{UNION}', U_UNION_LATEX)

# LaTeX-compatible interval notation
FMT_INTERVAL_LATEX = """
  static String _intervalLatex(String op, double b) {
    final bs = _fmtLatex(b);
    switch (op) {
      case '>': return '($bs, {INF})';
      case '{GEQ}': return '[$bs, {INF})';
      case '<': return '(-{INF}, $bs)';
      case '{LEQ}': return '(-{INF}, $bs]';
      default: return '';
    }
  }
""".replace('{INF}', U_INFINITY_LATEX_NR).replace('{GEQ}', U_GEQ).replace('{LEQ}', U_LEQ)

# ─── LINEAR SOLVER ─────────────────────────────────────────────────

LINEAR_CODE = DART_HEADER + """
class GeneratedLinearSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');

      final a = p.a - p.ra;
      final b = p.b - p.rb;

      if (a == 0) {
        final sat = _evalOp(b, p.op, 0);
        return SolveResult(
          answer: sat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: sat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
        );
      }

      final boundary = -b / a;
      final finalOp = a < 0 ? _flipOp(p.op) : p.op;
      return SolveResult(
        answer: 'x $finalOp ${_fmt(boundary)}',
        points: [boundary],
        intervalNotation: _interval(finalOp, boundary),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final a = p.a - p.ra;
    final b = p.b - p.rb;

    if (p.ra != 0 || p.rb != 0) {
      final leftExpr = '${_coefLatex(p.a)}x ${p.b >= 0 ? "+ ${_fmtLatex(p.b)}" : "- ${_fmtLatex(p.b.abs())}"}';
      String rightMove = '';
      if (p.ra != 0) {
        rightMove += p.ra > 0 ? ' - ${_coefLatex(p.ra)}x' : ' + ${_coefLatex(-p.ra)}x';
      }
      if (p.rb != 0) {
        rightMove += p.rb > 0 ? ' - ${_fmtLatex(p.rb)}' : ' + ${_fmtLatex(-p.rb)}';
      }
      final intermediate = '$leftExpr$rightMove ${_texOp(p.op)} 0';
      final simplified = '${_coefLatex(a)}x ${b >= 0 ? "+ ${_fmtLatex(b)}" : "- ${_fmtLatex(b.abs())}"} ${_texOp(p.op)} 0';

      List<String> _parts = [];
      if (p.ra != 0) {
        final absRa = p.ra.abs();
        final term = absRa == 1 ? 'x' : '${_fmt(absRa)}x';
        _parts.add(p.ra > 0 ? 'subtract $term' : 'add $term');
      }
      if (p.rb != 0) {
        _parts.add(p.rb > 0 ? 'subtract ${_fmt(p.rb.abs())}' : 'add ${_fmt(p.rb.abs())}');
      }
      final hint = '${_parts.join(', ')} from both sides';

      List<String>? _moveDetails;
      if (p.rb != 0) {
        _moveDetails = [
          '${_fmtLatex(p.b)} ${p.rb > 0 ? "-" : "+"} ${_fmtLatex(p.rb.abs())} = ${_fmtLatex(b)}'
        ];
      }

      if (intermediate != simplified) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: hint,
          details: _moveDetails,
          latex: intermediate,
          subLatex: [simplified],
        ));
      } else {
        steps.add(StepModel(
          stepNumber: n++,
          hint: hint,
          details: _moveDetails,
          latex: simplified,
        ));
      }
    }

    if (a == 0) {
      final sat = _evalOp(b, p.op, 0);
      steps.add(StepModel(
        stepNumber: n++,
        hint: sat ? 'Always true — no x term remains' : 'Always false — no x term remains',
        latex: sat ? r'(-\infty, \infty)' : r'\emptyset',
      ));
      return steps;
    }

    if (b != 0) {
      final isoDetails = <String>[
        b > 0
          ? '${_coefLatex(a)}x + ${_fmtLatex(b)} - ${_fmtLatex(b)} ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} 0 - ${_fmtLatex(b)}'
          : '${_coefLatex(a)}x - ${_fmtLatex(-b)} + ${_fmtLatex(-b)} ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} 0 + ${_fmtLatex(-b)}',
        '${_coefLatex(a)}x ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b)}',
      ];
      steps.add(StepModel(
        stepNumber: n++,
        hint: b > 0 ? 'Subtract ${_fmt(b)} from both sides' : 'Add ${_fmt(-b)} to both sides',
        details: isoDetails,
        latex: '${_coefLatex(a)}x ${_texOp(a < 0 ? _flipOp(p.op) : p.op)} ${_fmtLatex(-b)}',
      ));
    }

    if (a != 1 && a != -1) {
      final flip = a < 0;
      final divOp = flip ? _flipOp(p.op) : p.op;
      final divDetails = <String>[
        r'\\frac{' + '${_coefLatex(a)}x' + r'}{' + '${_fmtLatex(a)}' + r'} ' + '${_texOp(divOp)} ' + r'\\frac{' + '${_fmtLatex(-b)}' + r'}{' + '${_fmtLatex(a)}' + r'}',
        'x ${_texOp(divOp)} ${_fmtLatex(-b / a)}',
      ];
      if (flip) {
        divDetails.add(r'\\text{Dividing by }' + '${_fmt(a)}' + r'\\text{ flips }' + '${_texOp(p.op)}' + r'\\text{ to }' + '${_texOp(divOp)}');
      }
      steps.add(StepModel(
        stepNumber: n++,
        hint: flip ? 'Divide both sides by ${_fmt(a.abs())} and flip the inequality sign' : 'Divide both sides by ${_fmt(a)}',
        details: divDetails,
        latex: 'x ${_texOp(divOp)} ${_fmtLatex(-b / a)}',
      ));
    }

    final finalOp = a < 0 ? _flipOp(p.op) : p.op;
    steps.add(StepModel(
      stepNumber: n++,
      latex: _intervalLatex(finalOp, -b / a),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = _normalize(input);
    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);
    if (left.isEmpty || right.isEmpty) return null;

    final lp = _parseLinear(left);
    final rp = _parseLinear(right);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['x']!, b: lp['c']!,
      ra: rp['x']!, rb: rp['c']!,
    );
  }

  static String _normalize(String input) {
    return input
        .trim()
        .replaceAll('\\u2212', '-')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """')
        .replaceAll('=>', '""" + U_GEQ + """')
        .replaceAll('=<', '""" + U_LEQ + """')
        .replaceAll('x""" + U_SQUARED + """', 'x^2')
        .replaceAll('""" + U_SQUARED + """', '^2');
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TEXOP + FMT_FLIPOP + FMT_EVALOP + FMT_INTERVAL_LATEX + """

  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, """ + U_INFINITY + """)';
      case '""" + U_GEQ + """': return '[$bs, """ + U_INFINITY + """)';
      case '<': return '(-""" + U_INFINITY + """, $bs)';
      case '""" + U_LEQ + """': return '(-""" + U_INFINITY + """, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, ra, rb;
  const _Parsed({required this.op, required this.a, required this.b, required this.ra, required this.rb});
}
"""


# ─── QUADRATIC SOLVER ──────────────────────────────────────────────

QUAD_CODE = DART_HEADER + "import 'dart:math' as math;\n" + """
class GeneratedQuadraticSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');
      if (p.a == 0 && p.b == 0 && p.c == 0) {
        return SolveResult.error('Could not parse quadratic inequality.');
      }
      if (p.a == 0) return _solveLinear(p.b, p.c, p.op);

      final disc = p.b * p.b - 4 * p.a * p.c;

      if (disc < 0) {
        final allSat = p.a > 0
            ? (p.op == '>' || p.op == '""" + U_GEQ + """')
            : (p.op == '<' || p.op == '""" + U_LEQ + """');
        return SolveResult(
          answer: allSat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: allSat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
        );
      }

      final sqrtD = math.sqrt(disc);
      final r1 = (-p.b - sqrtD) / (2 * p.a);
      final r2 = (-p.b + sqrtD) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;

      if (disc == 0) {
        final root = -p.b / (2 * p.a);
        if (p.op == '""" + U_LEQ + """' || p.op == '""" + U_GEQ + """') {
          final ans = p.op == '""" + U_LEQ + """' ? 'x = ${_fmt(root)}' : 'All real numbers';
          final interval = p.op == '""" + U_LEQ + """' ? '{${_fmt(root)}}' : '(-""" + U_INFINITY + """, """ + U_INFINITY + """)';
          return SolveResult(answer: ans, points: [root], intervalNotation: interval);
        } else {
          final ans = p.op == '<' ? 'No solution' : 'x """ + U_GEQ + """ ${_fmt(root)}';
          final interval = p.op == '<'
              ? '""" + U_EMPTY + """'
              : '(-""" + U_INFINITY + """, ${_fmt(root)}) """ + U_UNION + """ (${_fmt(root)}, """ + U_INFINITY + """)';
          return SolveResult(answer: ans, points: [root], intervalNotation: interval);
        }
      }

      final strict = p.op == '<' || p.op == '>';
      final lb = strict ? '(' : '[';
      final rb = strict ? ')' : ']';
      final between = (p.op == '<' || p.op == '""" + U_LEQ + """') ? p.a > 0 : p.a < 0;

      if (between) {
        return SolveResult(
          answer: '${_fmt(lo)} ${p.op} x ${p.op} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '$lb${_fmt(lo)}, ${_fmt(hi)}$rb',
        );
      } else {
        final flipOp = _flipOp(p.op);
        return SolveResult(
          answer: 'x $flipOp ${_fmt(lo)} or x ${p.op} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '(-""" + U_INFINITY + """, ${_fmt(lo)})$rb """ + U_UNION + """ $lb${_fmt(hi)}, """ + U_INFINITY + """)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final disc = p.b * p.b - 4 * p.a * p.c;

    if (disc < 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Discriminant \\\\Delta = ${_fmt(disc)} < 0 — no real roots',
        details: [
          r'\Delta = b^2 - 4ac = ' + '${_fmtLatex(p.b)}^2 - 4(${_fmtLatex(p.a)})(${_fmtLatex(p.c)}) = ${_fmtLatex(disc)} < 0',
          r'\\text{No real roots, inequality is either always true or always false}',
        ],
        latex: '\\\\Delta = ${_fmtLatex(disc)} < 0 \\\\implies \\text{No real roots}',
      ));
      final result = solve(input);
      steps.add(StepModel(
        stepNumber: n++,
        latex: r'\\text{S.S} = ' + _toLatexInterval(result.intervalNotation ?? ''),
      ));
      return steps;
    }

    steps.add(StepModel(
      stepNumber: n++,
      hint: disc == 0 ? 'One repeated root' : 'Two distinct roots',
      details: [
        r'x = \\frac{-b \pm \sqrt{\Delta}}{2a} = \\frac{' + '${_fmtLatex(-p.b)} \\pm \\sqrt{${_fmtLatex(disc)}}' + r'}{2(' + '${_fmtLatex(p.a)}' + r')}',
        disc == 0
          ? r'x = ' + _fmtLatex(-p.b / (2 * p.a))
          : r'x_1 = ' + _fmtLatex((-p.b - math.sqrt(disc)) / (2 * p.a)) + r',\; x_2 = ' + _fmtLatex((-p.b + math.sqrt(disc)) / (2 * p.a)),
      ],
      latex: disc == 0
          ? r'x = ' + _fmtLatex(-p.b / (2 * p.a))
          : r'x_1 = ' + _fmtLatex((-p.b - math.sqrt(disc)) / (2 * p.a)) + ', x_2 = ' + _fmtLatex((-p.b + math.sqrt(disc)) / (2 * p.a)),

    ));

    if (disc > 0) {
      final r1 = (-p.b - math.sqrt(disc)) / (2 * p.a);
      final r2 = (-p.b + math.sqrt(disc)) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Test each region separated by the roots',
        latex: 'A: x < ${_fmtLatex(lo)}, B: ${_fmtLatex(lo)} < x < ${_fmtLatex(hi)}, C: x > ${_fmtLatex(hi)}',
      ));
    }

    final result = solve(input);
    steps.add(StepModel(
      stepNumber: n++,
      latex: r'\\text{S.S} = ' + _toLatexInterval(result.intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = _findOpIndex(s, op);
    if (idx == -1) return null;

    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final lp = _parseQuad(lhs);
    final rp = _parseQuad(rhs);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['a']! - rp['a']!,
      b: lp['b']! - rp['b']!,
      c: lp['c']! - rp['c']!,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static int _findOpIndex(String s, String op) {
    if (op == '>' || op == '<') {
      for (int i = s.length - 1; i >= 0; i--) {
        if (s[i] == op) {
          if (i + 1 < s.length && s[i + 1] == '=') continue;
          return i;
        }
      }
      return -1;
    }
    return s.indexOf(op);
  }

  static Map<String, double>? _parseQuad(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    double a = 0, b = 0, c = 0;
    final tokens = <String>[];
    int depth = 0;
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if (ch == '(') { depth++; cur += ch; }
      else if (ch == ')') { depth--; cur += ch; }
      else if ((ch == '+' || ch == '-') && i > 0 && depth == 0 && cur.isNotEmpty) {
        tokens.add(cur); cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      final t = tok.replaceAll('*', '');
      if (t.contains('x^2')) {
        final cs = t.substring(0, t.indexOf('x'));
        a += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else if (t.contains('x')) {
        final cs = t.substring(0, t.indexOf('x'));
        b += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else {
        final clean = t.startsWith('+') ? t.substring(1) : t;
        c += double.tryParse(clean) ?? 0;
      }
    }
    return {'a': a, 'b': b, 'c': c};
  }

  static SolveResult _solveLinear(double b, double c, String op) {
    if (b == 0) {
      final sat = _evalOp(c, op, 0);
      return SolveResult(
        answer: sat ? 'All real numbers' : 'No solution',
        points: [],
        intervalNotation: sat ? '(-""" + U_INFINITY + """, """ + U_INFINITY + """)' : '""" + U_EMPTY + """',
      );
    }
    final x = -c / b;
    final finalOp = b < 0 ? _flipOp(op) : op;
    return SolveResult(
      answer: 'x $finalOp ${_fmt(x)}',
      points: [x],
      intervalNotation: _interval(finalOp, x),
    );
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_FLIPOP + FMT_EVALOP + """

  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, """ + U_INFINITY + """)';
      case '""" + U_GEQ + """': return '[$bs, """ + U_INFINITY + """)';
      case '<': return '(-""" + U_INFINITY + """, $bs)';
      case '""" + U_LEQ + """': return '(-""" + U_INFINITY + """, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, c;
  const _Parsed({required this.op, required this.a, required this.b, required this.c});
}
"""


# ─── ABSOLUTE VALUE SOLVER ─────────────────────────────────────────

ABS_CODE = DART_HEADER + """
class GeneratedAbsoluteSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse absolute value inequality.');

      bool absOnLeft = p.absOnLeft;
      String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
      final isNarrow = effectiveOp == '<' || effectiveOp == '""" + U_LEQ + """';

      if (isNarrow) {
        if (p.k < 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '<') return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '""" + U_LEQ + """') {
          if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
          final root = -p.b / p.a;
          return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
        }
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final lb = effectiveOp == '<' ? '(' : '[';
        final rb = effectiveOp == '<' ? ')' : ']';
        return SolveResult(
          answer: '${_fmt(l)} $effectiveOp x $effectiveOp ${_fmt(h)}',
          points: [l, h],
          intervalNotation: '$lb${_fmt(l)}, ${_fmt(h)}$rb',
        );
      } else {
        if (p.k < 0) return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
        if (p.k == 0 && effectiveOp == '""" + U_GEQ + """') return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-""" + U_INFINITY + """, """ + U_INFINITY + """)');
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
        if (p.k == 0 && effectiveOp == '>') {
          final root = -p.b / p.a;
          final fR = _fmt(root);
          return SolveResult(answer: 'x """ + U_GEQ + """ $fR', points: [root], intervalNotation: '(-""" + U_INFINITY + """, $fR) """ + U_UNION + """ ($fR, """ + U_INFINITY + """)');
        }

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final b1 = effectiveOp == '>' ? ')' : ']';
        final b2 = effectiveOp == '>' ? '(' : '[';
        final fL = _fmt(l);
        final fH = _fmt(h);
        final flipOp = _flipOp(effectiveOp);
        return SolveResult(
          answer: 'x $flipOp $fL or x $effectiveOp $fH',
          points: [l, h],
          intervalNotation: '(-""" + U_INFINITY + """, $fL$b1 """ + U_UNION + """ $b2$fH, """ + U_INFINITY + """)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final innerStr = '${_coefLatex(p.a)}x ${p.b >= 0 ? "+ ${_fmtLatex(p.b)}" : "- ${_fmtLatex(p.b.abs())}"}';
    final kStr = _fmtLatex(p.k);
    bool absOnLeft = p.absOnLeft;
    String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
    final isNarrow = effectiveOp == '<' || effectiveOp == '""" + U_LEQ + """';

    if (isNarrow) {
      final nkStr = _fmtLatex(-p.k);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Write as -${_fmt(p.k)} < ... < ${_fmt(p.k)}',
        details: [
          r'\\text{If } |X| < k \\text{ then } -k < X < k',
          '$nkStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$nkStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
      ));
    } else {
      final flipOp = _flipOp(effectiveOp);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Split into two separate inequalities',
        details: [
          r'\\text{If } |X| > k \\text{ then } X < -k \\text{ or } X > k',
          '$innerStr ${_texOp(flipOp)} -$kStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$innerStr ${_texOp(flipOp)} -$kStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
      ));
    }

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    if (!s.contains('|')) return null;

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);

    bool absOnLeft;
    String absSide, constStr;
    if (left.contains('|')) {
      absSide = left; constStr = right; absOnLeft = true;
    } else if (right.contains('|')) {
      absSide = right; constStr = left; absOnLeft = false;
    } else {
      return null;
    }

    final inner = absSide.replaceAll('|', '');
    final k = double.tryParse(constStr);
    if (k == null) return null;

    final parsed = _parseLinear(inner);
    if (parsed == null) return null;

    return _Parsed(op: op, a: parsed['x']!, b: parsed['c']!, k: k, absOnLeft: absOnLeft);
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + FMT_FLIPOP + """
}

class _Parsed {
  final String op;
  final double a, b, k;
  final bool absOnLeft;
  const _Parsed({required this.op, required this.a, required this.b, required this.k, required this.absOnLeft});
}
"""


# ─── RATIONAL SOLVER ───────────────────────────────────────────────

RAT_CODE = DART_HEADER + """
class GeneratedRationalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse rational expression.');

      final intervals = _buildIntervals(p);
      if (intervals.isEmpty) {
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
      }

      return SolveResult(
        answer: intervals.join(' or '),
        points: _criticalPoints(p),
        intervalNotation: intervals.join(' """ + U_UNION + """ '),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final combStr = _linearStrLatex(p.combA, p.combC);
    final denStr = _linearStrLatex(p.denA, p.denC);

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Combine into a single fraction, set to zero',
      latex: r'\\frac{' + combStr + r'}{' + denStr + r'} ' + _texOp(p.op) + ' 0',
    ));

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Find critical points from numerator and denominator',
      latex: (p.combA != 0 ? '$combStr = 0' : '') + r' \\text{ and } ' + (p.denA != 0 ? '$denStr = 0' : ''),
    ));

    final intervals = _buildIntervals(p);
    final intervalStr = intervals.isEmpty ? '""" + U_EMPTY + """' : intervals.join(' """ + U_UNION + """ ');

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(intervalStr),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;
    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final slashIdx = lhs.indexOf('/');
    if (slashIdx == -1) return null;

    final numStr = lhs.substring(0, slashIdx).replaceAll('(', '').replaceAll(')', '');
    final denStr = lhs.substring(slashIdx + 1).replaceAll('(', '').replaceAll(')', '');
    final rhsVal = double.tryParse(rhs.trim()) ?? 0.0;

    final numP = _parseLinear(numStr);
    final denP = _parseLinear(denStr);
    if (numP == null || denP == null) return null;

    final numA = numP['x']!;
    final numC = numP['c']!;
    final denA = denP['x']!;
    final denC = denP['c']!;

    return _Parsed(
      op: op, numA: numA, numC: numC,
      denA: denA, denC: denC, rhs: rhsVal,
      combA: numA - rhsVal * denA,
      combC: numC - rhsVal * denC,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static List<double> _criticalPoints(_Parsed p) {
    final pts = <double>[];
    if (p.combA != 0) pts.add(-p.combC / p.combA);
    if (p.denA != 0) pts.add(-p.denC / p.denA);
    return pts.toSet().toList();
  }

  static bool _satisfies(double x, _Parsed p) {
    final den = p.denA * x + p.denC;
    if (den == 0) return false;
    final val = (p.combA * x + p.combC) / den;
    return _evalOp(val, p.op, 0);
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + FMT_EVALOP + """

  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }

  static List<String> _buildIntervals(_Parsed p) {
    final strict = p.op == '<' || p.op == '>';
    final denZero = p.denA != 0 ? -p.denC / p.denA : double.nan;
    final undefinedPts = <double>{if (!denZero.isNaN) denZero};

    final pts = _criticalPoints(p)..sort();
    if (pts.isEmpty) return [];

    final testPts = <double>[
      pts.first - 1,
      for (int i = 0; i < pts.length - 1; i++) (pts[i] + pts[i + 1]) / 2,
      pts.last + 1,
    ];

    final solution = <String>[];
    for (int i = 0; i < testPts.length; i++) {
      if (!_satisfies(testPts[i], p)) continue;
      if (i == 0) {
        final hi = pts[0];
        solution.add('(-""" + U_INFINITY + """, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      } else if (i == testPts.length - 1) {
        final lo = pts.last;
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, """ + U_INFINITY + """)');
      } else {
        final lo = pts[i - 1];
        final hi = pts[i];
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      }
    }
    return solution;
  }
}

class _Parsed {
  final String op;
  final double numA, numC, denA, denC, rhs, combA, combC;
  const _Parsed({
    required this.op,
    required this.numA, required this.numC,
    required this.denA, required this.denC,
    required this.rhs,
    required this.combA, required this.combC,
  });
}
"""


# ─── RADICAL SOLVER ────────────────────────────────────────────────

RAD_CODE = DART_HEADER + """
class GeneratedRadicalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse radical inequality.');

      // For sqrt(bx + c) op k
      if (p.k < 0) {
        if (p.op == '>' || p.op == '""" + U_GEQ + """') {
          return SolveResult(answer: 'x """ + U_GEQ + """ ${_fmt(-p.c / p.b)} (domain only)', points: [], intervalNotation: '');
        }
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: '""" + U_EMPTY + """');
      }

      // Domain: bx + c >= 0  =>  x >= -c/b (if b > 0) or x <= -c/b (if b < 0)
      final domainBoundary = -p.c / p.b;
      final domainReversed = p.b < 0;

      // Square: bx + c op k^2  =>  x op (k^2 - c) / b
      final kSq = p.k * p.k;
      final squaredBoundary = (kSq - p.c) / p.b;

      // Combine domain and squared inequality
      // Case analysis based on operation
      String answer, interval;
      final f = _fmt;
      final dB = f(domainBoundary);
      final sB = f(squaredBoundary);

      if (p.op == '<' || p.op == '""" + U_LEQ + """') {
        // sqrt(...) < k => domain AND x < (k^2 - c)/b
        // Upper bound is min of what?
        if (domainReversed) {
          answer = '$sB """ + U_LEQ + """ x """ + U_LEQ + """ $dB';
          interval = '[$sB, $dB]';
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'No solution';
            interval = '""" + U_EMPTY + """';
          } else {
            answer = '$dB """ + U_LEQ + """ x $sB';
            interval = '[$dB, $sB]';
          }
        }
      } else {
        // sqrt(...) > k => domain AND x > (k^2 - c)/b
        if (domainReversed) {
          if (squaredBoundary < domainBoundary) {
            answer = 'x """ + U_GEQ + """ $dB';
            interval = '[$dB, """ + U_INFINITY + """)';
          } else {
            answer = 'x """ + U_GEQ + """ $sB';
            interval = '[$sB, """ + U_INFINITY + """)';
          }
        } else {
          if (squaredBoundary < domainBoundary) {
            answer = 'x """ + U_GEQ + """ $dB';
            interval = '[$dB, """ + U_INFINITY + """)';
          } else {
            answer = 'x """ + U_GEQ + """ $sB';
            interval = '[$sB, """ + U_INFINITY + """)';
          }
        }
      }

      final pts = <double>[domainBoundary];
      if (squaredBoundary.isFinite && squaredBoundary != domainBoundary) {
        pts.add(squaredBoundary);
      }
      pts.sort();

      return SolveResult(answer: answer, points: pts, intervalNotation: interval);
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final radStrLatex = _linearStrLatex(p.b, p.c);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Radicand must be non-negative for real solutions',
      latex: r'\\text{' + radStrLatex + r'} \\geq 0',
    ));

    if (p.k >= 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Square both sides to eliminate the radical',
        details: [
          r'(' + radStrLatex + r')^2 ' + '${_texOp(p.op)} ' + '${_fmtLatex(p.k)}^2',
          '$radStrLatex ${_texOp(p.op)} ${_fmtLatex(p.k * p.k)}',
        ],
        latex: '$radStrLatex ${_texOp(p.op)} ${_fmtLatex(p.k * p.k)}',
      ));
    }

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .toLowerCase()
        .replaceAll(' ', '')
        .replaceAll('>=', '""" + U_GEQ + """')
        .replaceAll('<=', '""" + U_LEQ + """')
        .replaceAll('""" + U_SQUARED + """', '^2')
        .replaceAll('\\u221a', 'sqrt');

    final op = _extractOp(s);
    if (op == null) return null;

    // Find operator at top level (not inside parentheses)
    int depth = 0;
    int opIdx = -1;
    for (int i = 0; i < s.length; i++) {
      if (s[i] == '(') depth++;
      if (s[i] == ')') depth--;
      if (depth != 0) continue;
      if (s[i] == op) {
        // Check for multi-char ops
        if (op == '""" + U_GEQ + """' && i > 0) {
          if (s[i - 1] == '>') continue; // already matched with >
        }
        opIdx = i;
        break;
      }
    }
    if (opIdx == -1) return null;

    final lhs = s.substring(0, opIdx);
    final rhs = s.substring(opIdx + op.length);

    bool sqrtOnLeft = lhs.contains('sqrt');
    bool sqrtOnRight = rhs.contains('sqrt');
    if (!sqrtOnLeft && !sqrtOnRight) return null;

    String sqrtSide = sqrtOnLeft ? lhs : rhs;
    String constSide = sqrtOnLeft ? rhs : lhs;

    final sqrtMatch = RegExp(r'sqrt\(([^)]+)\)').firstMatch(sqrtSide);
    if (sqrtMatch == null) return null;
    final radicand = sqrtMatch.group(1)!;

    final k = double.tryParse(constSide.trim());
    if (k == null) return null;

    final parsed = _parseLinear(radicand);
    if (parsed == null) return null;

    return _Parsed(op: op, b: parsed['x']!, c: parsed['c']!, k: k);
  }

  static String? _extractOp(String s) {
    if (s.contains('""" + U_GEQ + """')) return '""" + U_GEQ + """';
    if (s.contains('""" + U_LEQ + """')) return '""" + U_LEQ + """';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }

""" + FMT_COMMON + FMT_COMMON_LATEX + FMT_TOLATEX + FMT_TEXOP + """
}

class _Parsed {
  final String op;
  final double b, c, k;
  const _Parsed({required this.op, required this.b, required this.c, required this.k});
}
"""


# ─── MAIN ──────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("MathCalcu - Dart Solver Generator")
    print("Generating SymPy-verified Dart solver files...")
    print("=" * 60)
    print()

    # Verify with SymPy first
    sympy_run_tests("Linear", [
        ("2*x + 1 > 5", "x > 2"),
        ("3*x - 7 <= 8", "x <= 5"),
        ("-4*x + 3 < 11", "x > -2"),
    ])
    sympy_run_tests("Quadratic", [
        ("x**2 - 4 > 0", "x < -2 or x > 2"),
        ("x**2 - 5*x + 6 <= 0", "2 <= x <= 3"),
    ])
    sympy_run_tests("Absolute", [
        ("Abs(x) < 3", "-3 < x < 3"),
        ("Abs(2*x - 1) >= 3", "x <= -1 or x >= 2"),
    ])
    sympy_run_tests("Rational", [
        ("(x+1)/(x-2) > 0", "x < -1 or x > 2"),
    ])

    print("\n" + "-" * 60)
    print("Generating Dart files...\n")

    write_dart("generated_linear_solver.dart", LINEAR_CODE)
    write_dart("generated_quadratic_solver.dart", QUAD_CODE)
    write_dart("generated_absolute_solver.dart", ABS_CODE)
    write_dart("generated_rational_solver.dart", RAT_CODE)
    write_dart("generated_radical_solver.dart", RAD_CODE)

    print("\n" + "=" * 60)
    print("Done! 5 Dart solver files generated in lib/midterm/solvers/inequalities_solver/")
    print("=" * 60)


if __name__ == "__main__":
    main()
