// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';


class GeneratedRationalSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse rational expression.');

      final intervals = _buildIntervals(p);
      if (intervals.isEmpty) {
        return const SolveResult(answer: 'No solution', points: [], intervalNotation: 'âˆ…');
      }

      return SolveResult(
        answer: intervals.join(' or '),
        points: _criticalPoints(p),
        intervalNotation: intervals.join(' âˆª '),
      );
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final combStr = _linearStrLatex(p.combA, p.combC);
    final denStr = _linearStrLatex(p.denA, p.denC);

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Combine into a single fraction, set to zero',
      latex: r'\frac{' + combStr + r'}{' + denStr + r'} ' + _texOp(p.op) + ' 0',
    ));

    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Find critical points from numerator and denominator',
      latex: (p.combA != 0 ? '$combStr = 0' : '') + r' \text{ and } ' + (p.denA != 0 ? '$denStr = 0' : ''),
    ));

    final intervals = _buildIntervals(p);
    final intervalStr = intervals.isEmpty ? 'âˆ…' : intervals.join(' âˆª ');

    steps.add(StepModel(
      stepNumber: n++,
      latex: _toLatexInterval(intervalStr),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll(' ', '')
        .replaceAll('>=', '≠¥')
        .replaceAll('<=', '≠¤');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;
    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final slashIdx = lhs.indexOf('/');
    if (slashIdx == -1) return null;

    final numStr = lhs.substring(0, slashIdx).replaceAll('(', '').replaceAll(')', '');
    final denStr = lhs.substring(slashIdx + 1).replaceAll('(', '').replaceAll(')', '');
    final rhsVal = double.tryParse(rhs.trim()) ?? 0.0;

    final numP = _parseLinear(numStr);
    final denP = _parseLinear(denStr);
    if (numP == null || denP == null) return null;

    final numA = numP['x']!;
    final numC = numP['c']!;
    final denA = denP['x']!;
    final denC = denP['c']!;

    return _Parsed(
      op: op, numA: numA, numC: numC,
      denA: denA, denC: denC, rhs: rhsVal,
      combA: numA - rhsVal * denA,
      combC: numC - rhsVal * denC,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('≠¥')) return '≠¥';
    if (s.contains('≠¤')) return '≠¤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static List<double> _criticalPoints(_Parsed p) {
    final pts = <double>[];
    if (p.combA != 0) pts.add(-p.combC / p.combA);
    if (p.denA != 0) pts.add(-p.denC / p.denA);
    return pts.toSet().toList();
  }

  static bool _satisfies(double x, _Parsed p) {
    final den = p.denA * x + p.denC;
    if (den == 0) return false;
    final val = (p.combA * x + p.combC) / den;
    return _evalOp(val, p.op, 0);
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\u221e', r'\infty')
        .replaceAll('\u2205', r'\emptyset')
        .replaceAll('\u222a', r'\cup');
  }

  static String _texOp(String op) {
    switch (op) {
      case '≠¥': return '\\geq';
      case '≠¤': return '\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }

  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '≠¥': return left >= right;
      case '≠¤': return left <= right;
      default: return false;
    }
  }


  static String _linearStrLatex(double a, double c) {
    if (a == 0) return _fmtLatex(c);
    final aStr = a == 1 ? 'x' : (a == -1 ? '-x' : '${_fmtLatex(a)}x');
    if (c == 0) return aStr;
    return '$aStr ${c > 0 ? "+" : "-"} ${_fmtLatex(c.abs())}';
  }

  static List<String> _buildIntervals(_Parsed p) {
    final strict = p.op == '<' || p.op == '>';
    final denZero = p.denA != 0 ? -p.denC / p.denA : double.nan;
    final undefinedPts = <double>{if (!denZero.isNaN) denZero};

    final pts = _criticalPoints(p)..sort();
    if (pts.isEmpty) return [];

    final testPts = <double>[
      pts.first - 1,
      for (int i = 0; i < pts.length - 1; i++) (pts[i] + pts[i + 1]) / 2,
      pts.last + 1,
    ];

    final solution = <String>[];
    for (int i = 0; i < testPts.length; i++) {
      if (!_satisfies(testPts[i], p)) continue;
      if (i == 0) {
        final hi = pts[0];
        solution.add('(-∞, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      } else if (i == testPts.length - 1) {
        final lo = pts.last;
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, ∞)');
      } else {
        final lo = pts[i - 1];
        final hi = pts[i];
        solution.add('${strict || undefinedPts.contains(lo) ? "(" : "["}${_fmt(lo)}, ${_fmt(hi)}${strict || undefinedPts.contains(hi) ? ")" : "]"}');
      }
    }
    return solution;
  }
}

class _Parsed {
  final String op;
  final double numA, numC, denA, denC, rhs, combA, combC;
  const _Parsed({
    required this.op,
    required this.numA, required this.numC,
    required this.denA, required this.denC,
    required this.rhs,
    required this.combA, required this.combC,
  });
}
