// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';

import 'dart:math' as math;

class GeneratedQuadraticSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse expression.');
      if (p.a == 0 && p.b == 0 && p.c == 0) {
        return SolveResult.error('Could not parse quadratic inequality.');
      }
      if (p.a == 0) return _solveLinear(p.b, p.c, p.op);

      final disc = p.b * p.b - 4 * p.a * p.c;

      if (disc < 0) {
        final allSat = p.a > 0
            ? (p.op == '>' || p.op == '≠¥')
            : (p.op == '<' || p.op == '≠¤');
        return SolveResult(
          answer: allSat ? 'All real numbers' : 'No solution',
          points: [],
          intervalNotation: allSat ? '(-∞, ∞)' : '∅',
        );
      }

      final sqrtD = math.sqrt(disc);
      final r1 = (-p.b - sqrtD) / (2 * p.a);
      final r2 = (-p.b + sqrtD) / (2 * p.a);
      final lo = r1 < r2 ? r1 : r2;
      final hi = r1 < r2 ? r2 : r1;

      if (disc == 0) {
        final root = -p.b / (2 * p.a);
        final opensUp = p.a > 0;
        if (opensUp) {
          if (p.op == '<') {
            return SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
          } else if (p.op == '≠¤') {
            return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
          } else if (p.op == '>') {
            return SolveResult(answer: 'x < ${_fmt(root)} or x > ${_fmt(root)}', points: [root],
              intervalNotation: '(-∞, ${_fmt(root)}) ∪ (${_fmt(root)}, ∞)');
          } else {
            return SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
          }
        } else {
          if (p.op == '<') {
            return SolveResult(answer: 'x < ${_fmt(root)} or x > ${_fmt(root)}', points: [root],
              intervalNotation: '(-∞, ${_fmt(root)}) ∪ (${_fmt(root)}, ∞)');
          } else if (p.op == '≠¤') {
            return SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
          } else if (p.op == '>') {
            return SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
          } else {
            return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
          }
        }
      }

      final strict = p.op == '<' || p.op == '>';
      final lb = strict ? '(' : '[';
      final rb = strict ? ')' : ']';
      final between = (p.op == '<' || p.op == '≠¤') ? p.a > 0 : p.a < 0;

      if (between) {
        final innerOp = strict ? '<' : '≠¤';
        return SolveResult(
          answer: '${_fmt(lo)} $innerOp x $innerOp ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '$lb${_fmt(lo)}, ${_fmt(hi)}$rb',
        );
      } else {
        return SolveResult(
          answer: 'x ${strict ? '<' : '≠¤'} ${_fmt(lo)} or x ${strict ? '>' : '≠¥'} ${_fmt(hi)}',
          points: [lo, hi],
          intervalNotation: '(-∞, ${_fmt(lo)}$rb ∪ $lb${_fmt(hi)}, ∞)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    // Step 1: Original inequality
    steps.add(StepModel(
      stepNumber: n++,
      latex: input.trim(),
    ));

    final disc = p.b * p.b - 4 * p.a * p.c;

    // Step 2: Standard form (if input wasn't already ax\u00b2+bx+c op 0)
    final aCoef = _coefLatex(p.a);
    final bCoef = p.b == 0 ? '' : (p.b > 0 ? '+ ${_fmtLatex(p.b)}x' : '- ${_fmtLatex(-p.b)}x');
    final cCoef = p.c == 0 ? '' : (p.c > 0 ? '+ ${_fmtLatex(p.c)}' : '- ${_fmtLatex(-p.c)}');
    final stdForm = '${aCoef}x^2 $bCoef $cCoef ${p.op} 0'.replaceAll('  ', ' ').trim();
    final inputNorm = input.trim().replaceAll(' ', '');
    if (stdForm.replaceAll(' ', '') != inputNorm) {
      final dets = [input.trim()];
      final opStr = _extractOp(inputNorm);
      if (opStr != null) {
        final opIdx = _findOpIndex(inputNorm, opStr);
        if (opIdx != -1) {
          final lhs = inputNorm.substring(0, opIdx).trim();
          final rhs = inputNorm.substring(opIdx + opStr.length).trim();
          if (rhs != '0') {
            final pRhs = rhs.contains('x') ? '($rhs)' : rhs;
            dets.add('$lhs - $pRhs ${p.op} $rhs - $pRhs');
            dets.add('$lhs - $pRhs ${p.op} 0');
          }
        }
      }
      if (dets.last != stdForm) dets.add(stdForm);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Move all terms to one side',
        details: dets,
        latex: stdForm,
      ));
    }

    // Step 3: Discriminant
    final bSq = p.b * p.b;
    final ac4 = 4 * p.a * p.c;
    steps.add(StepModel(
      stepNumber: n++,
      hint: disc < 0
          ? 'Negative discriminant \\Delta = ${_fmt(disc)} — no real roots'
          : disc == 0
              ? 'Zero discriminant \\Delta = 0 — one repeated root'
              : 'Positive discriminant \\Delta = ${_fmt(disc)} — two real roots',
      details: [
        r'\Delta = b^2 - 4ac',
        r'\Delta = (' + _fmtLatex(p.b) + ')^2 - 4(' + _fmtLatex(p.a) + ')(' + _fmtLatex(p.c) + ')',
        r'\Delta = ' + _fmtLatex(bSq) + ' - ' + _fmtLatex(ac4),
        r'\Delta = ' + _fmtLatex(disc),
      ],
      latex: r'\Delta = ' + _fmtLatex(disc),
    ));

    if (disc < 0) {
      final allSat = p.a > 0
          ? (p.op == '>' || p.op == '≠¥')
          : (p.op == '<' || p.op == '≠¤');
      steps.add(StepModel(
        stepNumber: n++,
        hint: allSat
            ? 'Always true — parabola never crosses x-axis'
            : 'Always false — parabola never crosses x-axis',
        details: [
          r'\Delta < 0 \implies \text{no real roots}',
          p.a > 0
              ? r'a > 0 \implies \text{parabola opens up, entirely above x-axis}'
              : r'a < 0 \implies \text{parabola opens down, entirely below x-axis}',
          allSat
              ? r'\text{Inequality holds for all } x'
              : r'\text{Inequality never holds}',
        ],
        latex: allSat ? r'(-\infty, \infty)' : r'\emptyset',
      ));
      return steps;
    }

    if (disc == 0) {
      final root = -p.b / (2 * p.a);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Repeated root at x = ${_fmt(root)}',
        details: [
          r'x = \frac{-b}{2a}',
          r'x = \frac{' + _fmtLatex(-p.b) + '}{2(' + _fmtLatex(p.a) + ')}',
          r'x = ' + _fmtLatex(root),
        ],
        latex: r'x = ' + _fmtLatex(root),
      ));
      final result = solve(input);
      steps.add(StepModel(
        stepNumber: n++,
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
      return steps;
    }

    // --- disc > 0: Two distinct real roots ---

    final sqrtD = math.sqrt(disc);
    final r1Val = (-p.b - sqrtD) / (2 * p.a);
    final r2Val = (-p.b + sqrtD) / (2 * p.a);
    final loLatex = r1Val < r2Val
        ? _fmtSurd(p.a, p.b, disc.round(), false)
        : _fmtSurd(p.a, p.b, disc.round(), true);
    final hiLatex = r1Val < r2Val
        ? _fmtSurd(p.a, p.b, disc.round(), true)
        : _fmtSurd(p.a, p.b, disc.round(), false);

    // Step 4: Quadratic formula -- find roots
    final negB = _fmtLatex(-p.b);
    final twoA = _fmtLatex(2 * p.a);
    final sqrtDisc = _sqrtSimplify(disc.round());
    final root1 = _fmtSurd(p.a, p.b, disc.round(), false);
    final root2 = _fmtSurd(p.a, p.b, disc.round(), true);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Find the roots',
      details: [
        r'x = \frac{-b \pm \sqrt{\Delta}}{2a}',
        r'x = \frac{' + negB + r' \pm \sqrt{' + _fmtLatex(disc) + '}}{' + twoA + '}',
        r'x_1 = \frac{' + negB + r' - ' + sqrtDisc + '}{' + twoA + '} = ' + root1,
        r'x_2 = \frac{' + negB + r' + ' + sqrtDisc + '}{' + twoA + '} = ' + root2,
      ],
      latex: r'x_1 = ' + root1 + r',\quad x_2 = ' + root2,
    ));

    // Step 5: Sign and solution
    final opensUp = p.a > 0;
    final between = (p.op == '<' || p.op == '≠¤') ? opensUp : !opensUp;

    String solLatex;
    if (between) {
      solLatex = loLatex + r' < x < ' + hiLatex;
    } else {
      solLatex = r'x < ' + loLatex + r' \quad\text{or}\quad x > ' + hiLatex;
    }

    steps.add(StepModel(
      stepNumber: n++,
      hint: opensUp ? 'Parabola opens upward' : 'Parabola opens downward',
      details: [
        opensUp
            ? r'\text{Positive outside, negative between}'
            : r'\text{Negative outside, positive between}',
        solLatex,
      ],
      latex: solLatex,
    ));

    final result = solve(input);
    steps.add(StepModel(
      stepNumber: n++,
      hint: 'Solution in interval notation',
      latex: _toLatexInterval(result.intervalNotation ?? ''),
    ));

    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('²', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '≠¥')
        .replaceAll('<=', '≠¤');

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = _findOpIndex(s, op);
    if (idx == -1) return null;

    final lhs = s.substring(0, idx);
    final rhs = s.substring(idx + op.length);

    final lp = _parseQuad(lhs);
    final rp = _parseQuad(rhs);
    if (lp == null || rp == null) return null;

    return _Parsed(
      op: op,
      a: lp['a']! - rp['a']!,
      b: lp['b']! - rp['b']!,
      c: lp['c']! - rp['c']!,
    );
  }

  static String? _extractOp(String s) {
    if (s.contains('≠¥')) return '≠¥';
    if (s.contains('≠¤')) return '≠¤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static int _findOpIndex(String s, String op) {
    if (op == '>' || op == '<') {
      for (int i = s.length - 1; i >= 0; i--) {
        if (s[i] == op) {
          if (i + 1 < s.length && s[i + 1] == '=') continue;
          return i;
        }
      }
      return -1;
    }
    return s.indexOf(op);
  }

  static Map<String, double>? _parseQuad(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    double a = 0, b = 0, c = 0;
    final tokens = <String>[];
    int depth = 0;
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if (ch == '(') { depth++; cur += ch; }
      else if (ch == ')') { depth--; cur += ch; }
      else if ((ch == '+' || ch == '-') && i > 0 && depth == 0 && cur.isNotEmpty) {
        tokens.add(cur); cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      final t = tok.replaceAll('*', '');
      if (t.contains('x^2')) {
        final cs = t.substring(0, t.indexOf('x'));
        a += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else if (t.contains('x')) {
        final cs = t.substring(0, t.indexOf('x'));
        b += cs.isEmpty || cs == '+' ? 1 : cs == '-' ? -1 : (double.tryParse(cs) ?? 0);
      } else {
        final clean = t.startsWith('+') ? t.substring(1) : t;
        c += double.tryParse(clean) ?? 0;
      }
    }
    return {'a': a, 'b': b, 'c': c};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }

  static SolveResult _solveLinear(double b, double c, String op) {
    if (b == 0) {
      final sat = _evalOp(c, op, 0);
      return SolveResult(
        answer: sat ? 'All real numbers' : 'No solution',
        points: [],
        intervalNotation: sat ? '(-∞, ∞)' : '∅',
      );
    }
    final x = -c / b;
    final finalOp = b < 0 ? _flipOp(op) : op;
    return SolveResult(
      answer: 'x $finalOp ${_fmt(x)}',
      points: [x],
      intervalNotation: _interval(finalOp, x),
    );
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\u221e', r'\infty')
        .replaceAll('\u2205', r'\emptyset')
        .replaceAll('\u222a', r'\cup');
  }

  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '≠¥': return '≠¤';
      case '≠¤': return '≠¥';
      default: return op;
    }
  }

  static bool _evalOp(double left, String op, double right) {
    switch (op) {
      case '>': return left > right;
      case '<': return left < right;
      case '≠¥': return left >= right;
      case '≠¤': return left <= right;
      default: return false;
    }
  }


  /// Simplify sqrt(n) into a\sqrt{b} form, e.g. sqrt(32) -> 4\sqrt{2}
  static String _sqrtSimplify(int n) {
    if (n <= 0) return '0';
    int sq = 1, rem = n;
    for (int i = 2; i * i <= rem; i++) {
      while (rem % (i * i) == 0) {
        sq *= i;
        rem ~/= (i * i);
      }
    }
    if (rem == 1) return sq.toString();
    if (sq == 1) return r'\sqrt{' + rem.toString() + '}';
    return sq.toString() + r'\sqrt{' + rem.toString() + '}';
  }

  /// Format a root (-b +/- sqrt(Delta))/(2a) in simplified radical form.
  /// Falls back to _fmtLatex for rational roots.
  static String _fmtSurd(double a, double b, int disc, bool plus) {
    final sqrtVal = math.sqrt(disc);
    if (sqrtVal == sqrtVal.roundToDouble()) {
      return _fmtLatex((-b + (plus ? 1 : -1) * sqrtVal) / (2 * a));
    }
    final sqrtStr = _sqrtSimplify(disc);
    final sign = plus ? '+' : '-';
    if (b == 0) {
      final den = (2 * a).round();
      final m = RegExp(r'^(\d+)\\sqrt\{').firstMatch(sqrtStr);
      if (m != null) {
        final coeff = int.parse(m[1]!);
        if (den != 0 && coeff % den.abs() == 0) {
          final c = coeff ~/ den.abs();
          final rem = sqrtStr.substring(m[1]!.length);
          if (a < 0) return (plus ? '-' : '') + (c == 1 ? '' : c.toString()) + rem;
          return (plus ? '' : '-') + (c == 1 ? '' : c.toString()) + rem;
        }
      }
      if (den == 1 || den == -1) return (plus ? '' : '-') + sqrtStr;
      return r'\frac{' + (a < 0 == plus ? '' : '-') + sqrtStr + '}{' + _fmtLatex(2 * a) + '}';
    }
    return r'\frac{' + _fmtLatex(-b) + ' ' + sign + ' ' + sqrtStr + '}{' + _fmtLatex(2 * a) + '}';
  }

  static String _interval(String op, double b) {
    final bs = _fmt(b);
    switch (op) {
      case '>': return '($bs, ∞)';
      case '≠¥': return '[$bs, ∞)';
      case '<': return '(-∞, $bs)';
      case '≠¤': return '(-∞, $bs]';
      default: return '';
    }
  }
}

class _Parsed {
  final String op;
  final double a, b, c;
  const _Parsed({required this.op, required this.a, required this.b, required this.c});
}
