// AUTOGENERATED by math_generator.py - DO NOT EDIT
// Algorithms verified against SymPy for correctness.

import 'package:calculus_system/core/solve_result.dart';
import 'package:calculus_system/core/step_model.dart';


class GeneratedAbsoluteSolver {
  static SolveResult solve(String input) {
    try {
      final p = _parse(input);
      if (p == null) return SolveResult.error('Could not parse absolute value inequality.');

      bool absOnLeft = p.absOnLeft;
      String effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
      final isNarrow = effectiveOp == '<' || effectiveOp == '≠¤';

      if (isNarrow) {
        if (p.k < 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '<') return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '≠¤') {
          if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
          final root = -p.b / p.a;
          return SolveResult(answer: 'x = ${_fmt(root)}', points: [root], intervalNotation: '{${_fmt(root)}}');
        }
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final lb = effectiveOp == '<' ? '(' : '[';
        final rb = effectiveOp == '<' ? ')' : ']';
        return SolveResult(
          answer: '${_fmt(l)} $effectiveOp x $effectiveOp ${_fmt(h)}',
          points: [l, h],
          intervalNotation: '$lb${_fmt(l)}, ${_fmt(h)}$rb',
        );
      } else {
        if (p.k < 0) return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
        if (p.k == 0 && effectiveOp == '≠¥') return const SolveResult(answer: 'All real numbers', points: [], intervalNotation: '(-∞, ∞)');
        if (p.a == 0) return const SolveResult(answer: 'No solution', points: [], intervalNotation: '∅');
        if (p.k == 0 && effectiveOp == '>') {
          final root = -p.b / p.a;
          final fR = _fmt(root);
          return SolveResult(answer: 'x < $fR or x > $fR', points: [root], intervalNotation: '(-∞, $fR) ∪ ($fR, ∞)');
        }

        final v1 = (-p.k - p.b) / p.a;
        final v2 = (p.k - p.b) / p.a;
        final l = v1 < v2 ? v1 : v2;
        final h = v1 < v2 ? v2 : v1;
        final b1 = effectiveOp == '>' ? ')' : ']';
        final b2 = effectiveOp == '>' ? '(' : '[';
        final fL = _fmt(l);
        final fH = _fmt(h);
        final flipOp = _flipOp(effectiveOp);
        return SolveResult(
          answer: 'x $flipOp $fL or x $effectiveOp $fH',
          points: [l, h],
          intervalNotation: '(-∞, $fL$b1 ∪ $b2$fH, ∞)',
        );
      }
    } catch (e) {
      return SolveResult.error('Error: $e');
    }
  }

  static List<StepModel> getSteps(String input) {
    final steps = <StepModel>[];
    final p = _parse(input);
    if (p == null) return steps;

    int n = 1;

    // Step 1: Show the original inequality with proper absolute value delimiters
    steps.add(StepModel(
      stepNumber: n++,
      latex: _absToLatex(input.trim()),
    ));

    final innerStr = p.b == 0 ? '${_coefLatex(p.a)}x' : '${_coefLatex(p.a)}x ${p.b >= 0 ? "+ ${_fmtLatex(p.b)}" : "- ${_fmtLatex(p.b.abs())}"}';
    final kStr = _fmtLatex(p.k);
    final absOnLeft = p.absOnLeft;
    final effectiveOp = absOnLeft ? p.op : _flipOp(p.op);
    final isNarrow = effectiveOp == '<' || effectiveOp == '≠¤';

    // ---- Edge cases ----
    if (p.a == 0) {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'No variable term — evaluate the constant directly',
        latex: _toLatexInterval(solve(input).intervalNotation ?? ''),
      ));
      return steps;
    }

    if (p.k < 0) {
      if (isNarrow) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Absolute value is always \u2265 0, so it can never be < ${_fmt(p.k)}',
          latex: r'\emptyset',
        ));
      } else {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Absolute value is always \u2265 0, which is always \u2265 ${_fmt(p.k)}',
          latex: r'(-\infty, \infty)',
        ));
      }
      return steps;
    }

    if (p.k == 0 && effectiveOp == '<') {
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Absolute value is always \u2265 0, so |expr| < 0 has no solution',
        latex: r'\emptyset',
      ));
      return steps;
    }

    if (p.k == 0 && effectiveOp == '>') {
      // |ax+b| > 0  =>  ax+b ≠  0  =>  x ≠  -b/a
      final root = _fmtLatex(-p.b / p.a);
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Absolute value is always \u2265 0, so |expr| > 0 means expr \u2260 0',
        latex: r'x \neq ' + root,
      ));
      steps.add(StepModel(
        stepNumber: n++,
        latex: r'(-\infty, ' + root + r') \cup (' + root + r', \infty)',
      ));
      return steps;
    }

    // ---- Common computations ----
    final flipOp = _flipOp(effectiveOp);
    final negKStr = _fmtLatex(-p.k);
    final v1 = (-p.k - p.b) / p.a;
    final v2 = (p.k - p.b) / p.a;
    final l = v1 < v2 ? v1 : v2;
    final h = v1 < v2 ? v2 : v1;
    final result = solve(input);

    // Pre-compute formatted strings for reuse
    final leftConst = _fmtLatex(-p.k - p.b);
    final rightConst = _fmtLatex(p.k - p.b);

    if (isNarrow) {
      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // NARROW CASE  |ax+b| < k  →  -k < ax+b < k
      // Steps: Rule → Isolate x-term → Divide → Interval
      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 2: Apply Theorem 1 — |X| < k  =>  -k < X < k
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Apply Theorem 1',
        details: [
          _absToLatex(input.trim()),
          r'\Downarrow',
          r'\text{Theorem 1: } |X| ' + _texOp(effectiveOp) + r' k \Rightarrow -k ' + _texOp(effectiveOp) + r' X ' + _texOp(effectiveOp) + r' k',
          '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
      ));

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 3: Isolate x-term — subtract/add constant
      if (p.b != 0) {
        final bAbs = _fmtLatex(p.b.abs());
        final bStr = _fmtLatex(p.b);
        final amount = p.b > 0 ? _fmt(p.b) : _fmt(-p.b);
        final opWord = p.b > 0 ? 'Subtract' : 'Add';
        final leftArith = p.b > 0
            ? '$negKStr - $bAbs'
            : '$negKStr + $bAbs';
        final midArith = p.b > 0
            ? '${_coefLatex(p.a)}x + $bStr - $bAbs'
            : '${_coefLatex(p.a)}x - $bAbs + $bAbs';
        final rightArith = p.b > 0
            ? '$kStr - $bAbs'
            : '$kStr + $bAbs';
        steps.add(StepModel(
          stepNumber: n++,
          hint: '$opWord $amount from all three parts',
          details: [
            '$negKStr ${_texOp(effectiveOp)} $innerStr ${_texOp(effectiveOp)} $kStr',
            r'\Downarrow',
            '$leftArith ${_texOp(effectiveOp)} $midArith ${_texOp(effectiveOp)} $rightArith',
            r'\Downarrow',
            '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
          ],
          latex: '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
        ));
      }

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 4: Divide by x-coefficient
      if (p.a != 1 && p.a != -1) {
        final finalOpNarrow = p.a < 0 ? _flipOp(effectiveOp) : effectiveOp;
        final aStr = _fmtLatex(p.a);
        steps.add(StepModel(
          stepNumber: n++,
          hint: p.a < 0
              ? 'Divide all parts by ${_fmt(p.a.abs())}, flip inequality signs'
              : 'Divide all parts by ${_fmt(p.a)}',
          details: [
            '$leftConst ${_texOp(effectiveOp)} ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rightConst',
            r'\Downarrow',
            r'\frac{' + _fmtLatex(-p.k - p.b) + '}{' + aStr + '} ' + _texOp(finalOpNarrow) + r' \frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(finalOpNarrow) + r' \frac{' + _fmtLatex(p.k - p.b) + '}{' + aStr + '}',
            r'\Downarrow',
            '${_fmtLatex(l)} ${_texOp(finalOpNarrow)} x ${_texOp(finalOpNarrow)} ${_fmtLatex(h)}',
          ],
          latex: '${_fmtLatex(l)} ${_texOp(finalOpNarrow)} x ${_texOp(finalOpNarrow)} ${_fmtLatex(h)}',
        ));
      } else if (p.a == -1) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Multiply all parts by -1, flip signs',
          details: [
            '$leftConst ${_texOp(effectiveOp)} -x ${_texOp(effectiveOp)} $rightConst',
            r'\Downarrow',
            '${_fmtLatex(l)} ${_texOp(effectiveOp)} x ${_texOp(effectiveOp)} ${_fmtLatex(h)}',
          ],
          latex: '${_fmtLatex(l)} ${_texOp(effectiveOp)} x ${_texOp(effectiveOp)} ${_fmtLatex(h)}',
        ));
      }

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Final: Interval notation
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Write solution in interval notation',
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
    } else {
      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // WIDE CASE  |ax+b| > k  →  ax+b < -k  OR  ax+b > k
      // Steps: Rule → Solve Left → Solve Right → Combine → Interval
      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 2: Apply Theorem 2 — |X| > k  =>  X < -k  or  X > k
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Apply Theorem 2',
        details: [
          _absToLatex(input.trim()),
          r'\Downarrow',
          r'\text{Theorem 2: } |X| ' + _texOp(effectiveOp) + r' k \Rightarrow X ' + _texOp(flipOp) + r' -k \text{ or } X ' + _texOp(effectiveOp) + r' k',
          '$innerStr ${_texOp(flipOp)} $negKStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
        ],
        latex: '$innerStr ${_texOp(flipOp)} $negKStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
      ));

      final leftOp = p.a < 0 ? _flipOp(flipOp) : flipOp;
      final leftVal = _fmtLatex((-p.k - p.b) / p.a);
      final rightOp = p.a < 0 ? _flipOp(effectiveOp) : effectiveOp;
      final rightVal = _fmtLatex((p.k - p.b) / p.a);

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 3: Isolate x-term in both branches
      if (p.b != 0) {
        final lConst = _fmtLatex(-p.k - p.b);
        final rConst = _fmtLatex(p.k - p.b);
        final bAbs = _fmtLatex(p.b.abs());
        final bStr = _fmtLatex(p.b);
        final amount = p.b > 0 ? _fmt(p.b) : _fmt(-p.b);
        final opWord = p.b > 0 ? 'Subtract' : 'Add';
        final leftArith = p.b > 0
            ? '$negKStr - $bAbs'
            : '$negKStr + $bAbs';
        final rightArith = p.b > 0
            ? '$kStr - $bAbs'
            : '$kStr + $bAbs';
        final midArith = p.b > 0
            ? '${_coefLatex(p.a)}x + $bStr - $bAbs'
            : '${_coefLatex(p.a)}x - $bAbs + $bAbs';
        steps.add(StepModel(
          stepNumber: n++,
          hint: '$opWord $amount from both sides of each inequality',
          details: [
            '$innerStr ${_texOp(flipOp)} $negKStr \\text{ or } $innerStr ${_texOp(effectiveOp)} $kStr',
            r'\Downarrow',
            '$midArith ${_texOp(flipOp)} $leftArith \\text{ or } $midArith ${_texOp(effectiveOp)} $rightArith',
            r'\Downarrow',
            '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lConst \\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rConst',
          ],
          latex: '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lConst \\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rConst',
        ));
      }

      // Step 4: Divide by coefficient in both branches
      if (p.a != 1 && p.a != -1) {
        final aStr = _fmtLatex(p.a);
        final lcStr = _fmtLatex(-p.k - p.b);
        final rcStr = _fmtLatex(p.k - p.b);
        steps.add(StepModel(
          stepNumber: n++,
          hint: p.a < 0 ? 'Divide both sides by ${_fmt(p.a.abs())}, flip signs' : 'Divide both sides by ${_fmt(p.a)}',
          details: [
            '${_coefLatex(p.a)}x ${_texOp(flipOp)} $lcStr \\text{ or } ${_coefLatex(p.a)}x ${_texOp(effectiveOp)} $rcStr',
            r'\Downarrow',
            r'\frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(leftOp) + r' \frac{' + lcStr + '}{' + aStr + '} \\text{ or } ' + r'\frac{' + _coefLatex(p.a) + 'x}{' + aStr + '} ' + _texOp(rightOp) + r' \frac{' + rcStr + '}{' + aStr + '}',
            r'\Downarrow',
            'x ${_texOp(leftOp)} ${leftVal} \\text{ or } x ${_texOp(rightOp)} ${rightVal}',
          ],
          latex: 'x ${_texOp(leftOp)} ${leftVal} \\text{ or } x ${_texOp(rightOp)} ${rightVal}',
        ));
      } else if (p.a == -1) {
        steps.add(StepModel(
          stepNumber: n++,
          hint: 'Multiply by -1, flip signs',
          details: [
            'x ${_texOp(leftOp)} ${leftVal} \\text{ or } x ${_texOp(rightOp)} ${rightVal}',
          ],
          latex: 'x ${_texOp(leftOp)} ${leftVal} \\text{ or } x ${_texOp(rightOp)} ${rightVal}',
        ));
      }

      // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      // Step 5: Interval notation
      steps.add(StepModel(
        stepNumber: n++,
        hint: 'Combine into solution set',
        latex: _toLatexInterval(result.intervalNotation ?? ''),
      ));
    }


    return steps;
  }

  static _Parsed? _parse(String input) {
    String s = input
        .trim()
        .replaceAll('−', '-')
        .replaceAll('²', '^2')
        .replaceAll(' ', '')
        .replaceAll('>=', '≠¥')
        .replaceAll('<=', '≠¤');

    if (!s.contains('|')) return null;

    final op = _extractOp(s);
    if (op == null) return null;

    final idx = s.indexOf(op);
    if (idx == -1) return null;

    final left = s.substring(0, idx);
    final right = s.substring(idx + op.length);

    bool absOnLeft;
    String absSide, constStr;
    if (left.contains('|')) {
      absSide = left; constStr = right; absOnLeft = true;
    } else if (right.contains('|')) {
      absSide = right; constStr = left; absOnLeft = false;
    } else {
      return null;
    }

    final inner = absSide.replaceAll('|', '');
    final k = double.tryParse(constStr);
    if (k == null) return null;

    final parsed = _parseLinear(inner);
    if (parsed == null) return null;

    return _Parsed(op: op, a: parsed['x']!, b: parsed['c']!, k: k, absOnLeft: absOnLeft);
  }

  static String? _extractOp(String s) {
    if (s.contains('≠¥')) return '≠¥';
    if (s.contains('≠¤')) return '≠¤';
    if (s.contains('>')) return '>';
    if (s.contains('<')) return '<';
    return null;
  }

  static Map<String, double>? _parseLinear(String expr) {
    expr = expr.trim().replaceAll(' ', '');
    if (expr.isEmpty) return null;
    double xCoef = 0, constant = 0;
    final tokens = <String>[];
    String cur = '';
    for (int i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if ((ch == '+' || ch == '-') && i > 0) {
        if (cur.isNotEmpty) tokens.add(cur);
        cur = ch;
      } else { cur += ch; }
    }
    if (cur.isNotEmpty) tokens.add(cur);
    for (final tok in tokens) {
      if (tok.contains('x')) {
        final cs = tok.split('x')[0];
        if (cs.isEmpty || cs == '+') xCoef += 1;
        else if (cs == '-') xCoef -= 1;
        else xCoef += double.tryParse(cs) ?? 0;
      } else {
        constant += double.tryParse(tok) ?? 0;
      }
    }
    return {'x': xCoef, 'c': constant};
  }

  static String _coefLatex(double a) {
    if (a == 1) return '';
    if (a == -1) return '-';
    return _fmtLatex(a);
  }


  static String _fmt(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? '-∞' : '∞');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        return '$sn/$sd';
      }
    }
    return n.toStringAsFixed(4);
  }

  static int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

  static String _fmtLatex(double n) {
    if (n == 0) return '0';
    if (!n.isFinite) return n.isNaN ? 'NaN' : (n.isNegative ? r'-\infty' : r'\infty');
    if (n == n.roundToDouble()) return n.toInt().toString();
    for (int d = 2; d <= 20; d++) {
      final num = (n * d).round();
      if ((num / d - n).abs() < 1e-9) {
        int g = _gcd(num.abs(), d);
        final sn = num ~/ g;
        final sd = d ~/ g;
        if (sd == 1) return sn.toString();
        if (sn < 0) return r'-\frac{' + (-sn).toString() + '}{' + sd.toString() + '}';
        return r'\frac{' + sn.toString() + '}{' + sd.toString() + '}';
      }
    }
    return n.toStringAsFixed(4);
  }

  static String _toLatexInterval(String s) {
    return s
        .replaceAll('\u221e', r'\infty')
        .replaceAll('\u2205', r'\emptyset')
        .replaceAll('\u222a', r'\cup');
  }

  static String _texOp(String op) {
    switch (op) {
      case '≠¥': return '\\geq';
      case '≠¤': return '\\leq';
      case '>': return '>';
      case '<': return '<';
      default: return op;
    }
  }

  static String _flipOp(String op) {
    switch (op) {
      case '>': return '<';
      case '<': return '>';
      case '≠¥': return '≠¤';
      case '≠¤': return '≠¥';
      default: return op;
    }
  }


  /// Replace |...| with \lvert...\rvert for proper LaTeX absolute value rendering
  static String _absToLatex(String s) {
    final buf = StringBuffer();
    bool inAbs = false;
    for (int i = 0; i < s.length; i++) {
      if (s[i] == '|') {
        if (!inAbs) {
          buf.write(r'\lvert ');
          inAbs = true;
        } else {
          buf.write(r' \rvert');
          inAbs = false;
        }
      } else {
        buf.write(s[i]);
      }
    }
    return buf.toString();
  }
}

class _Parsed {
  final String op;
  final double a, b, k;
  final bool absOnLeft;
  const _Parsed({required this.op, required this.a, required this.b, required this.k, required this.absOnLeft});
}
