import 'package:flutter/material.dart';
import '../../core/solve_result.dart';
import 'package:provider/provider.dart';
import '../../theme/theme_provider.dart';

// ─────────────────────────────────────────────────────────────
// ANSWER CARD — shared widget used by ALL modules
// Shows the final answer. Tap to reveal the StepsDrawer.
// Do NOT edit this file per-module. Theming is via accentColor.
// ─────────────────────────────────────────────────────────────

class AnswerCard extends StatefulWidget {
  final SolveResult result;
  final Color accentColor;
  final VoidCallback onTap; // triggers StepsDrawer in parent

  const AnswerCard({
    super.key,
    required this.result,
    required this.accentColor,
    required this.onTap,
  });

  @override
  State<AnswerCard> createState() => _AnswerCardState();
}

class _AnswerCardState extends State<AnswerCard>
    with SingleTickerProviderStateMixin {
  late final AnimationController _pulseCtrl;
  late final Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    _pulseCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 180),
    );
    _scale = Tween<double>(begin: 1.0, end: 0.96).animate(
      CurvedAnimation(parent: _pulseCtrl, curve: Curves.easeInOut),
    );
  }

  @override
  void dispose() {
    _pulseCtrl.dispose();
    super.dispose();
  }

  void _handleTap() {
    _pulseCtrl.forward().then((_) => _pulseCtrl.reverse());
    widget.onTap();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.result.hasError) return const SizedBox.shrink();

    final accent = widget.accentColor;

    return ScaleTransition(
      scale: _scale,
      child: GestureDetector(
        onTap: _handleTap,
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                accent.withValues(alpha :0.15),
                accent.withValues(alpha :0.05),
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
            borderRadius: BorderRadius.circular(18),
            border: Border.all(color: accent.withValues(alpha :0.3), width: 1),
          ),
          child: Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Answer',
                      style: TextStyle(
                        fontSize: 11,
                        fontWeight: FontWeight.w600,
                        color: accent.withValues(alpha :0.7),
                        letterSpacing: 1.2,
                      ),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      widget.result.answer,
                      style: TextStyle(
                        fontSize: 26,
                        fontWeight: FontWeight.w700,
                        color: context.watch<ThemeProvider>().textPrimary,
                        letterSpacing: -0.5,
                      ),
                      overflow: TextOverflow.ellipsis,
                      maxLines: 2,
                      softWrap: true,
                    ),
                    if (widget.result.intervalNotation != null) ...[
                      const SizedBox(height: 4),
                      Text(
                        widget.result.intervalNotation!,
                        style: TextStyle(
                          fontSize: 13,
                          color: context.watch<ThemeProvider>().textSecondary,
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              // "tap for steps" hint
              Column(
                children: [
                  Icon(Icons.menu_book_rounded, color: accent, size: 20),
                  const SizedBox(height: 4),
                  Text(
                    'Steps',
                    style: TextStyle(
                      fontSize: 10,
                      color: accent.withValues(alpha :0.7),
                      letterSpacing: 0.5,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
