name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.6'   # ← ADDED

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: dart run flutter_launcher_icons

      - name: Build Release APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/MathCalcu.apk

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: MathCalcu Latest
          files: build/app/outputs/flutter-apk/MathCalcu.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true             # ← ADDEDflutter --version